package com.webside.business.model;

import java.util.Date;

import org.apache.ibatis.type.Alias;

import com.webside.base.basemodel.BaseEntity;

/**
 * Database Table Remarks:
 *   公司授权表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_company_auth
 *
 * @mbg.generated do_not_delete_during_merge Sat Dec 16 06:27:51 CST 2017
 */
@Alias("companyAuthEntity")
public class CompanyAuthEntity extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1258474049985166421L;

	private Long companyId;
    
    private Long userId;
    
    private Long creatorId;

    private Integer authCode;
    
	private String note;
    
    private Date createTime;

    private Date updateTime;
    
	/*
	 * 前端列表页使用
	 */
	private String userName;
	private String companyName;

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getAuthCode() {
		return authCode;
	}

	public void setAuthCode(Integer authCode) {
		this.authCode = authCode;
	}

	public Long getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
}