package com.webside.business.mapper;

import com.webside.business.model.CodeEntity;
import com.webside.business.model.CodeEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CodeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code
     *
     * @mbg.generated Thu Feb 08 23:27:53 CST 2018
     */
    long countByExample(CodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code
     *
     * @mbg.generated Thu Feb 08 23:27:53 CST 2018
     */
    int deleteByExample(CodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code
     *
     * @mbg.generated Thu Feb 08 23:27:53 CST 2018
     */
    int insert(CodeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code
     *
     * @mbg.generated Thu Feb 08 23:27:53 CST 2018
     */
    int insertSelective(CodeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code
     *
     * @mbg.generated Thu Feb 08 23:27:53 CST 2018
     */
    List<CodeEntity> selectByExample(CodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code
     *
     * @mbg.generated Thu Feb 08 23:27:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") CodeEntity record, @Param("example") CodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code
     *
     * @mbg.generated Thu Feb 08 23:27:53 CST 2018
     */
    int updateByExample(@Param("record") CodeEntity record, @Param("example") CodeEntityExample example);
}