package com.webside.business.mapper;

import com.webside.business.model.EnforceEntrustEntity;
import com.webside.business.model.EnforceEntrustEntityExample;
import com.webside.business.model.RepairEntity;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface EnforceEntrustEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust
     *
     * @mbg.generated Sat Jan 27 19:31:12 CST 2018
     */
    long countByExample(EnforceEntrustEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust
     *
     * @mbg.generated Sat Jan 27 19:31:12 CST 2018
     */
    int deleteByExample(EnforceEntrustEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust
     *
     * @mbg.generated Sat Jan 27 19:31:12 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust
     *
     * @mbg.generated Sat Jan 27 19:31:12 CST 2018
     */
    int insert(EnforceEntrustEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust
     *
     * @mbg.generated Sat Jan 27 19:31:12 CST 2018
     */
    int insertSelective(EnforceEntrustEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust
     *
     * @mbg.generated Sat Jan 27 19:31:12 CST 2018
     */
    List<EnforceEntrustEntity> selectByExample(EnforceEntrustEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust
     *
     * @mbg.generated Sat Jan 27 19:31:12 CST 2018
     */
    EnforceEntrustEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust
     *
     * @mbg.generated Sat Jan 27 19:31:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") EnforceEntrustEntity record, @Param("example") EnforceEntrustEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust
     *
     * @mbg.generated Sat Jan 27 19:31:12 CST 2018
     */
    int updateByExample(@Param("record") EnforceEntrustEntity record, @Param("example") EnforceEntrustEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust
     *
     * @mbg.generated Sat Jan 27 19:31:12 CST 2018
     */
    int updateByPrimaryKeySelective(EnforceEntrustEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust
     *
     * @mbg.generated Sat Jan 27 19:31:12 CST 2018
     */
    int updateByPrimaryKey(EnforceEntrustEntity record);
    public List<Map> entrustFacilityListByPage(Map<String, Object> parameter);
    public List<Map> facilityListByPage(Map<String, Object> parameter);
    public int deleteEntrustByIds(List<String> ids);
    public List<Map> inquiryList(Map pmap);
    public List<Map> taskEntrustList(Map<String, Object> parameter);
    public List<EnforceEntrustEntity> selectEnforceEntrust(Map<String, Object> parameter);
}