package com.webside.business.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.webside.base.basemapper.BaseMapper;
import com.webside.business.model.ExamineOrganEntity;
import com.webside.business.model.ExamineOrganEntityExample;

public interface ExamineOrganMapper  extends BaseMapper<ExamineOrganEntity, Long>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_examine_organ
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    long countByExample(ExamineOrganEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_examine_organ
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    int deleteByExample(ExamineOrganEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_examine_organ
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_examine_organ
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    int insert(ExamineOrganEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_examine_organ
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    int insertSelective(ExamineOrganEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_examine_organ
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    List<ExamineOrganEntity> selectByExample(ExamineOrganEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_examine_organ
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    ExamineOrganEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_examine_organ
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") ExamineOrganEntity record, @Param("example") ExamineOrganEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_examine_organ
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    int updateByExample(@Param("record") ExamineOrganEntity record, @Param("example") ExamineOrganEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_examine_organ
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    int updateByPrimaryKeySelective(ExamineOrganEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_examine_organ
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    int updateByPrimaryKey(ExamineOrganEntity record);
}