package com.webside.business.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FacilityEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public FacilityEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCidIsNull() {
            addCriterion("cid is null");
            return (Criteria) this;
        }

        public Criteria andCidIsNotNull() {
            addCriterion("cid is not null");
            return (Criteria) this;
        }

        public Criteria andCidEqualTo(Integer value) {
            addCriterion("cid =", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotEqualTo(Integer value) {
            addCriterion("cid <>", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThan(Integer value) {
            addCriterion("cid >", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cid >=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThan(Integer value) {
            addCriterion("cid <", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThanOrEqualTo(Integer value) {
            addCriterion("cid <=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidIn(List<Integer> values) {
            addCriterion("cid in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotIn(List<Integer> values) {
            addCriterion("cid not in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidBetween(Integer value1, Integer value2) {
            addCriterion("cid between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotBetween(Integer value1, Integer value2) {
            addCriterion("cid not between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andFactoryNoIsNull() {
            addCriterion("factory_no is null");
            return (Criteria) this;
        }

        public Criteria andFactoryNoIsNotNull() {
            addCriterion("factory_no is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryNoEqualTo(String value) {
            addCriterion("factory_no =", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoNotEqualTo(String value) {
            addCriterion("factory_no <>", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoGreaterThan(String value) {
            addCriterion("factory_no >", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoGreaterThanOrEqualTo(String value) {
            addCriterion("factory_no >=", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoLessThan(String value) {
            addCriterion("factory_no <", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoLessThanOrEqualTo(String value) {
            addCriterion("factory_no <=", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoLike(String value) {
            addCriterion("factory_no like", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoNotLike(String value) {
            addCriterion("factory_no not like", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoIn(List<String> values) {
            addCriterion("factory_no in", values, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoNotIn(List<String> values) {
            addCriterion("factory_no not in", values, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoBetween(String value1, String value2) {
            addCriterion("factory_no between", value1, value2, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoNotBetween(String value1, String value2) {
            addCriterion("factory_no not between", value1, value2, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFacilityNameIsNull() {
            addCriterion("facility_name is null");
            return (Criteria) this;
        }

        public Criteria andFacilityNameIsNotNull() {
            addCriterion("facility_name is not null");
            return (Criteria) this;
        }

        public Criteria andFacilityNameEqualTo(String value) {
            addCriterion("facility_name =", value, "facilityName");
            return (Criteria) this;
        }

        public Criteria andFacilityNameNotEqualTo(String value) {
            addCriterion("facility_name <>", value, "facilityName");
            return (Criteria) this;
        }

        public Criteria andFacilityNameGreaterThan(String value) {
            addCriterion("facility_name >", value, "facilityName");
            return (Criteria) this;
        }

        public Criteria andFacilityNameGreaterThanOrEqualTo(String value) {
            addCriterion("facility_name >=", value, "facilityName");
            return (Criteria) this;
        }

        public Criteria andFacilityNameLessThan(String value) {
            addCriterion("facility_name <", value, "facilityName");
            return (Criteria) this;
        }

        public Criteria andFacilityNameLessThanOrEqualTo(String value) {
            addCriterion("facility_name <=", value, "facilityName");
            return (Criteria) this;
        }

        public Criteria andFacilityNameLike(String value) {
            addCriterion("facility_name like", value, "facilityName");
            return (Criteria) this;
        }

        public Criteria andFacilityNameNotLike(String value) {
            addCriterion("facility_name not like", value, "facilityName");
            return (Criteria) this;
        }

        public Criteria andFacilityNameIn(List<String> values) {
            addCriterion("facility_name in", values, "facilityName");
            return (Criteria) this;
        }

        public Criteria andFacilityNameNotIn(List<String> values) {
            addCriterion("facility_name not in", values, "facilityName");
            return (Criteria) this;
        }

        public Criteria andFacilityNameBetween(String value1, String value2) {
            addCriterion("facility_name between", value1, value2, "facilityName");
            return (Criteria) this;
        }

        public Criteria andFacilityNameNotBetween(String value1, String value2) {
            addCriterion("facility_name not between", value1, value2, "facilityName");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeIsNull() {
            addCriterion("facility_type is null");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeIsNotNull() {
            addCriterion("facility_type is not null");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeEqualTo(String value) {
            addCriterion("facility_type =", value, "facilityType");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeNotEqualTo(String value) {
            addCriterion("facility_type <>", value, "facilityType");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeGreaterThan(String value) {
            addCriterion("facility_type >", value, "facilityType");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeGreaterThanOrEqualTo(String value) {
            addCriterion("facility_type >=", value, "facilityType");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeLessThan(String value) {
            addCriterion("facility_type <", value, "facilityType");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeLessThanOrEqualTo(String value) {
            addCriterion("facility_type <=", value, "facilityType");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeLike(String value) {
            addCriterion("facility_type like", value, "facilityType");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeNotLike(String value) {
            addCriterion("facility_type not like", value, "facilityType");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeIn(List<String> values) {
            addCriterion("facility_type in", values, "facilityType");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeNotIn(List<String> values) {
            addCriterion("facility_type not in", values, "facilityType");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeBetween(String value1, String value2) {
            addCriterion("facility_type between", value1, value2, "facilityType");
            return (Criteria) this;
        }

        public Criteria andFacilityTypeNotBetween(String value1, String value2) {
            addCriterion("facility_type not between", value1, value2, "facilityType");
            return (Criteria) this;
        }

        public Criteria andModelIsNull() {
            addCriterion("model is null");
            return (Criteria) this;
        }

        public Criteria andModelIsNotNull() {
            addCriterion("model is not null");
            return (Criteria) this;
        }

        public Criteria andModelEqualTo(String value) {
            addCriterion("model =", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotEqualTo(String value) {
            addCriterion("model <>", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThan(String value) {
            addCriterion("model >", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThanOrEqualTo(String value) {
            addCriterion("model >=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThan(String value) {
            addCriterion("model <", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThanOrEqualTo(String value) {
            addCriterion("model <=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLike(String value) {
            addCriterion("model like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotLike(String value) {
            addCriterion("model not like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelIn(List<String> values) {
            addCriterion("model in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotIn(List<String> values) {
            addCriterion("model not in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelBetween(String value1, String value2) {
            addCriterion("model between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotBetween(String value1, String value2) {
            addCriterion("model not between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andAccuracyIsNull() {
            addCriterion("accuracy is null");
            return (Criteria) this;
        }

        public Criteria andAccuracyIsNotNull() {
            addCriterion("accuracy is not null");
            return (Criteria) this;
        }

        public Criteria andAccuracyEqualTo(String value) {
            addCriterion("accuracy =", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyNotEqualTo(String value) {
            addCriterion("accuracy <>", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyGreaterThan(String value) {
            addCriterion("accuracy >", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyGreaterThanOrEqualTo(String value) {
            addCriterion("accuracy >=", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyLessThan(String value) {
            addCriterion("accuracy <", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyLessThanOrEqualTo(String value) {
            addCriterion("accuracy <=", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyLike(String value) {
            addCriterion("accuracy like", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyNotLike(String value) {
            addCriterion("accuracy not like", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyIn(List<String> values) {
            addCriterion("accuracy in", values, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyNotIn(List<String> values) {
            addCriterion("accuracy not in", values, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyBetween(String value1, String value2) {
            addCriterion("accuracy between", value1, value2, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyNotBetween(String value1, String value2) {
            addCriterion("accuracy not between", value1, value2, "accuracy");
            return (Criteria) this;
        }

        public Criteria andTestRangeIsNull() {
            addCriterion("test_range is null");
            return (Criteria) this;
        }

        public Criteria andTestRangeIsNotNull() {
            addCriterion("test_range is not null");
            return (Criteria) this;
        }

        public Criteria andTestRangeEqualTo(String value) {
            addCriterion("test_range =", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeNotEqualTo(String value) {
            addCriterion("test_range <>", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeGreaterThan(String value) {
            addCriterion("test_range >", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeGreaterThanOrEqualTo(String value) {
            addCriterion("test_range >=", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeLessThan(String value) {
            addCriterion("test_range <", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeLessThanOrEqualTo(String value) {
            addCriterion("test_range <=", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeLike(String value) {
            addCriterion("test_range like", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeNotLike(String value) {
            addCriterion("test_range not like", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeIn(List<String> values) {
            addCriterion("test_range in", values, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeNotIn(List<String> values) {
            addCriterion("test_range not in", values, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeBetween(String value1, String value2) {
            addCriterion("test_range between", value1, value2, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeNotBetween(String value1, String value2) {
            addCriterion("test_range not between", value1, value2, "testRange");
            return (Criteria) this;
        }

        public Criteria andBelongOrganIsNull() {
            addCriterion("belong_organ is null");
            return (Criteria) this;
        }

        public Criteria andBelongOrganIsNotNull() {
            addCriterion("belong_organ is not null");
            return (Criteria) this;
        }

        public Criteria andBelongOrganEqualTo(String value) {
            addCriterion("belong_organ =", value, "belongOrgan");
            return (Criteria) this;
        }

        public Criteria andBelongOrganNotEqualTo(String value) {
            addCriterion("belong_organ <>", value, "belongOrgan");
            return (Criteria) this;
        }

        public Criteria andBelongOrganGreaterThan(String value) {
            addCriterion("belong_organ >", value, "belongOrgan");
            return (Criteria) this;
        }

        public Criteria andBelongOrganGreaterThanOrEqualTo(String value) {
            addCriterion("belong_organ >=", value, "belongOrgan");
            return (Criteria) this;
        }

        public Criteria andBelongOrganLessThan(String value) {
            addCriterion("belong_organ <", value, "belongOrgan");
            return (Criteria) this;
        }

        public Criteria andBelongOrganLessThanOrEqualTo(String value) {
            addCriterion("belong_organ <=", value, "belongOrgan");
            return (Criteria) this;
        }

        public Criteria andBelongOrganLike(String value) {
            addCriterion("belong_organ like", value, "belongOrgan");
            return (Criteria) this;
        }

        public Criteria andBelongOrganNotLike(String value) {
            addCriterion("belong_organ not like", value, "belongOrgan");
            return (Criteria) this;
        }

        public Criteria andBelongOrganIn(List<String> values) {
            addCriterion("belong_organ in", values, "belongOrgan");
            return (Criteria) this;
        }

        public Criteria andBelongOrganNotIn(List<String> values) {
            addCriterion("belong_organ not in", values, "belongOrgan");
            return (Criteria) this;
        }

        public Criteria andBelongOrganBetween(String value1, String value2) {
            addCriterion("belong_organ between", value1, value2, "belongOrgan");
            return (Criteria) this;
        }

        public Criteria andBelongOrganNotBetween(String value1, String value2) {
            addCriterion("belong_organ not between", value1, value2, "belongOrgan");
            return (Criteria) this;
        }

        public Criteria andManageNoIsNull() {
            addCriterion("manage_no is null");
            return (Criteria) this;
        }

        public Criteria andManageNoIsNotNull() {
            addCriterion("manage_no is not null");
            return (Criteria) this;
        }

        public Criteria andManageNoEqualTo(String value) {
            addCriterion("manage_no =", value, "manageNo");
            return (Criteria) this;
        }

        public Criteria andManageNoNotEqualTo(String value) {
            addCriterion("manage_no <>", value, "manageNo");
            return (Criteria) this;
        }

        public Criteria andManageNoGreaterThan(String value) {
            addCriterion("manage_no >", value, "manageNo");
            return (Criteria) this;
        }

        public Criteria andManageNoGreaterThanOrEqualTo(String value) {
            addCriterion("manage_no >=", value, "manageNo");
            return (Criteria) this;
        }

        public Criteria andManageNoLessThan(String value) {
            addCriterion("manage_no <", value, "manageNo");
            return (Criteria) this;
        }

        public Criteria andManageNoLessThanOrEqualTo(String value) {
            addCriterion("manage_no <=", value, "manageNo");
            return (Criteria) this;
        }

        public Criteria andManageNoLike(String value) {
            addCriterion("manage_no like", value, "manageNo");
            return (Criteria) this;
        }

        public Criteria andManageNoNotLike(String value) {
            addCriterion("manage_no not like", value, "manageNo");
            return (Criteria) this;
        }

        public Criteria andManageNoIn(List<String> values) {
            addCriterion("manage_no in", values, "manageNo");
            return (Criteria) this;
        }

        public Criteria andManageNoNotIn(List<String> values) {
            addCriterion("manage_no not in", values, "manageNo");
            return (Criteria) this;
        }

        public Criteria andManageNoBetween(String value1, String value2) {
            addCriterion("manage_no between", value1, value2, "manageNo");
            return (Criteria) this;
        }

        public Criteria andManageNoNotBetween(String value1, String value2) {
            addCriterion("manage_no not between", value1, value2, "manageNo");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNull() {
            addCriterion("manufacturer is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNotNull() {
            addCriterion("manufacturer is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerEqualTo(String value) {
            addCriterion("manufacturer =", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotEqualTo(String value) {
            addCriterion("manufacturer <>", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThan(String value) {
            addCriterion("manufacturer >", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThanOrEqualTo(String value) {
            addCriterion("manufacturer >=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThan(String value) {
            addCriterion("manufacturer <", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThanOrEqualTo(String value) {
            addCriterion("manufacturer <=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLike(String value) {
            addCriterion("manufacturer like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotLike(String value) {
            addCriterion("manufacturer not like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerIn(List<String> values) {
            addCriterion("manufacturer in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotIn(List<String> values) {
            addCriterion("manufacturer not in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerBetween(String value1, String value2) {
            addCriterion("manufacturer between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotBetween(String value1, String value2) {
            addCriterion("manufacturer not between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andUsePlaceIsNull() {
            addCriterion("use_place is null");
            return (Criteria) this;
        }

        public Criteria andUsePlaceIsNotNull() {
            addCriterion("use_place is not null");
            return (Criteria) this;
        }

        public Criteria andUsePlaceEqualTo(String value) {
            addCriterion("use_place =", value, "usePlace");
            return (Criteria) this;
        }

        public Criteria andUsePlaceNotEqualTo(String value) {
            addCriterion("use_place <>", value, "usePlace");
            return (Criteria) this;
        }

        public Criteria andUsePlaceGreaterThan(String value) {
            addCriterion("use_place >", value, "usePlace");
            return (Criteria) this;
        }

        public Criteria andUsePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("use_place >=", value, "usePlace");
            return (Criteria) this;
        }

        public Criteria andUsePlaceLessThan(String value) {
            addCriterion("use_place <", value, "usePlace");
            return (Criteria) this;
        }

        public Criteria andUsePlaceLessThanOrEqualTo(String value) {
            addCriterion("use_place <=", value, "usePlace");
            return (Criteria) this;
        }

        public Criteria andUsePlaceLike(String value) {
            addCriterion("use_place like", value, "usePlace");
            return (Criteria) this;
        }

        public Criteria andUsePlaceNotLike(String value) {
            addCriterion("use_place not like", value, "usePlace");
            return (Criteria) this;
        }

        public Criteria andUsePlaceIn(List<String> values) {
            addCriterion("use_place in", values, "usePlace");
            return (Criteria) this;
        }

        public Criteria andUsePlaceNotIn(List<String> values) {
            addCriterion("use_place not in", values, "usePlace");
            return (Criteria) this;
        }

        public Criteria andUsePlaceBetween(String value1, String value2) {
            addCriterion("use_place between", value1, value2, "usePlace");
            return (Criteria) this;
        }

        public Criteria andUsePlaceNotBetween(String value1, String value2) {
            addCriterion("use_place not between", value1, value2, "usePlace");
            return (Criteria) this;
        }

        public Criteria andFunctionIsNull() {
            addCriterion("function is null");
            return (Criteria) this;
        }

        public Criteria andFunctionIsNotNull() {
            addCriterion("function is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionEqualTo(String value) {
            addCriterion("function =", value, "function");
            return (Criteria) this;
        }

        public Criteria andFunctionNotEqualTo(String value) {
            addCriterion("function <>", value, "function");
            return (Criteria) this;
        }

        public Criteria andFunctionGreaterThan(String value) {
            addCriterion("function >", value, "function");
            return (Criteria) this;
        }

        public Criteria andFunctionGreaterThanOrEqualTo(String value) {
            addCriterion("function >=", value, "function");
            return (Criteria) this;
        }

        public Criteria andFunctionLessThan(String value) {
            addCriterion("function <", value, "function");
            return (Criteria) this;
        }

        public Criteria andFunctionLessThanOrEqualTo(String value) {
            addCriterion("function <=", value, "function");
            return (Criteria) this;
        }

        public Criteria andFunctionLike(String value) {
            addCriterion("function like", value, "function");
            return (Criteria) this;
        }

        public Criteria andFunctionNotLike(String value) {
            addCriterion("function not like", value, "function");
            return (Criteria) this;
        }

        public Criteria andFunctionIn(List<String> values) {
            addCriterion("function in", values, "function");
            return (Criteria) this;
        }

        public Criteria andFunctionNotIn(List<String> values) {
            addCriterion("function not in", values, "function");
            return (Criteria) this;
        }

        public Criteria andFunctionBetween(String value1, String value2) {
            addCriterion("function between", value1, value2, "function");
            return (Criteria) this;
        }

        public Criteria andFunctionNotBetween(String value1, String value2) {
            addCriterion("function not between", value1, value2, "function");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceUnitIsNull() {
            addCriterion("price_unit is null");
            return (Criteria) this;
        }

        public Criteria andPriceUnitIsNotNull() {
            addCriterion("price_unit is not null");
            return (Criteria) this;
        }

        public Criteria andPriceUnitEqualTo(String value) {
            addCriterion("price_unit =", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitNotEqualTo(String value) {
            addCriterion("price_unit <>", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitGreaterThan(String value) {
            addCriterion("price_unit >", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitGreaterThanOrEqualTo(String value) {
            addCriterion("price_unit >=", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitLessThan(String value) {
            addCriterion("price_unit <", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitLessThanOrEqualTo(String value) {
            addCriterion("price_unit <=", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitLike(String value) {
            addCriterion("price_unit like", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitNotLike(String value) {
            addCriterion("price_unit not like", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitIn(List<String> values) {
            addCriterion("price_unit in", values, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitNotIn(List<String> values) {
            addCriterion("price_unit not in", values, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitBetween(String value1, String value2) {
            addCriterion("price_unit between", value1, value2, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitNotBetween(String value1, String value2) {
            addCriterion("price_unit not between", value1, value2, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andLocalSourceIsNull() {
            addCriterion("local_source is null");
            return (Criteria) this;
        }

        public Criteria andLocalSourceIsNotNull() {
            addCriterion("local_source is not null");
            return (Criteria) this;
        }

        public Criteria andLocalSourceEqualTo(String value) {
            addCriterion("local_source =", value, "localSource");
            return (Criteria) this;
        }

        public Criteria andLocalSourceNotEqualTo(String value) {
            addCriterion("local_source <>", value, "localSource");
            return (Criteria) this;
        }

        public Criteria andLocalSourceGreaterThan(String value) {
            addCriterion("local_source >", value, "localSource");
            return (Criteria) this;
        }

        public Criteria andLocalSourceGreaterThanOrEqualTo(String value) {
            addCriterion("local_source >=", value, "localSource");
            return (Criteria) this;
        }

        public Criteria andLocalSourceLessThan(String value) {
            addCriterion("local_source <", value, "localSource");
            return (Criteria) this;
        }

        public Criteria andLocalSourceLessThanOrEqualTo(String value) {
            addCriterion("local_source <=", value, "localSource");
            return (Criteria) this;
        }

        public Criteria andLocalSourceLike(String value) {
            addCriterion("local_source like", value, "localSource");
            return (Criteria) this;
        }

        public Criteria andLocalSourceNotLike(String value) {
            addCriterion("local_source not like", value, "localSource");
            return (Criteria) this;
        }

        public Criteria andLocalSourceIn(List<String> values) {
            addCriterion("local_source in", values, "localSource");
            return (Criteria) this;
        }

        public Criteria andLocalSourceNotIn(List<String> values) {
            addCriterion("local_source not in", values, "localSource");
            return (Criteria) this;
        }

        public Criteria andLocalSourceBetween(String value1, String value2) {
            addCriterion("local_source between", value1, value2, "localSource");
            return (Criteria) this;
        }

        public Criteria andLocalSourceNotBetween(String value1, String value2) {
            addCriterion("local_source not between", value1, value2, "localSource");
            return (Criteria) this;
        }

        public Criteria andFacilityStateIsNull() {
            addCriterion("facility_state is null");
            return (Criteria) this;
        }

        public Criteria andFacilityStateIsNotNull() {
            addCriterion("facility_state is not null");
            return (Criteria) this;
        }

        public Criteria andFacilityStateEqualTo(String value) {
            addCriterion("facility_state =", value, "facilityState");
            return (Criteria) this;
        }

        public Criteria andFacilityStateNotEqualTo(String value) {
            addCriterion("facility_state <>", value, "facilityState");
            return (Criteria) this;
        }

        public Criteria andFacilityStateGreaterThan(String value) {
            addCriterion("facility_state >", value, "facilityState");
            return (Criteria) this;
        }

        public Criteria andFacilityStateGreaterThanOrEqualTo(String value) {
            addCriterion("facility_state >=", value, "facilityState");
            return (Criteria) this;
        }

        public Criteria andFacilityStateLessThan(String value) {
            addCriterion("facility_state <", value, "facilityState");
            return (Criteria) this;
        }

        public Criteria andFacilityStateLessThanOrEqualTo(String value) {
            addCriterion("facility_state <=", value, "facilityState");
            return (Criteria) this;
        }

        public Criteria andFacilityStateLike(String value) {
            addCriterion("facility_state like", value, "facilityState");
            return (Criteria) this;
        }

        public Criteria andFacilityStateNotLike(String value) {
            addCriterion("facility_state not like", value, "facilityState");
            return (Criteria) this;
        }

        public Criteria andFacilityStateIn(List<String> values) {
            addCriterion("facility_state in", values, "facilityState");
            return (Criteria) this;
        }

        public Criteria andFacilityStateNotIn(List<String> values) {
            addCriterion("facility_state not in", values, "facilityState");
            return (Criteria) this;
        }

        public Criteria andFacilityStateBetween(String value1, String value2) {
            addCriterion("facility_state between", value1, value2, "facilityState");
            return (Criteria) this;
        }

        public Criteria andFacilityStateNotBetween(String value1, String value2) {
            addCriterion("facility_state not between", value1, value2, "facilityState");
            return (Criteria) this;
        }

        public Criteria andIfTestIsNull() {
            addCriterion("if_test is null");
            return (Criteria) this;
        }

        public Criteria andIfTestIsNotNull() {
            addCriterion("if_test is not null");
            return (Criteria) this;
        }

        public Criteria andIfTestEqualTo(String value) {
            addCriterion("if_test =", value, "ifTest");
            return (Criteria) this;
        }

        public Criteria andIfTestNotEqualTo(String value) {
            addCriterion("if_test <>", value, "ifTest");
            return (Criteria) this;
        }

        public Criteria andIfTestGreaterThan(String value) {
            addCriterion("if_test >", value, "ifTest");
            return (Criteria) this;
        }

        public Criteria andIfTestGreaterThanOrEqualTo(String value) {
            addCriterion("if_test >=", value, "ifTest");
            return (Criteria) this;
        }

        public Criteria andIfTestLessThan(String value) {
            addCriterion("if_test <", value, "ifTest");
            return (Criteria) this;
        }

        public Criteria andIfTestLessThanOrEqualTo(String value) {
            addCriterion("if_test <=", value, "ifTest");
            return (Criteria) this;
        }

        public Criteria andIfTestLike(String value) {
            addCriterion("if_test like", value, "ifTest");
            return (Criteria) this;
        }

        public Criteria andIfTestNotLike(String value) {
            addCriterion("if_test not like", value, "ifTest");
            return (Criteria) this;
        }

        public Criteria andIfTestIn(List<String> values) {
            addCriterion("if_test in", values, "ifTest");
            return (Criteria) this;
        }

        public Criteria andIfTestNotIn(List<String> values) {
            addCriterion("if_test not in", values, "ifTest");
            return (Criteria) this;
        }

        public Criteria andIfTestBetween(String value1, String value2) {
            addCriterion("if_test between", value1, value2, "ifTest");
            return (Criteria) this;
        }

        public Criteria andIfTestNotBetween(String value1, String value2) {
            addCriterion("if_test not between", value1, value2, "ifTest");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateIsNull() {
            addCriterion("purchase_date is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateIsNotNull() {
            addCriterion("purchase_date is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateEqualTo(Date value) {
            addCriterion("purchase_date =", value, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateNotEqualTo(Date value) {
            addCriterion("purchase_date <>", value, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateGreaterThan(Date value) {
            addCriterion("purchase_date >", value, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateGreaterThanOrEqualTo(Date value) {
            addCriterion("purchase_date >=", value, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateLessThan(Date value) {
            addCriterion("purchase_date <", value, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateLessThanOrEqualTo(Date value) {
            addCriterion("purchase_date <=", value, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateIn(List<Date> values) {
            addCriterion("purchase_date in", values, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateNotIn(List<Date> values) {
            addCriterion("purchase_date not in", values, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateBetween(Date value1, Date value2) {
            addCriterion("purchase_date between", value1, value2, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateNotBetween(Date value1, Date value2) {
            addCriterion("purchase_date not between", value1, value2, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateIsNull() {
            addCriterion("expiration_date is null");
            return (Criteria) this;
        }

        public Criteria andExpirationDateIsNotNull() {
            addCriterion("expiration_date is not null");
            return (Criteria) this;
        }

        public Criteria andExpirationDateEqualTo(Date value) {
            addCriterion("expiration_date =", value, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateNotEqualTo(Date value) {
            addCriterion("expiration_date <>", value, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateGreaterThan(Date value) {
            addCriterion("expiration_date >", value, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("expiration_date >=", value, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateLessThan(Date value) {
            addCriterion("expiration_date <", value, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateLessThanOrEqualTo(Date value) {
            addCriterion("expiration_date <=", value, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateIn(List<Date> values) {
            addCriterion("expiration_date in", values, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateNotIn(List<Date> values) {
            addCriterion("expiration_date not in", values, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateBetween(Date value1, Date value2) {
            addCriterion("expiration_date between", value1, value2, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateNotBetween(Date value1, Date value2) {
            addCriterion("expiration_date not between", value1, value2, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachIsNull() {
            addCriterion("facility_attach is null");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachIsNotNull() {
            addCriterion("facility_attach is not null");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachEqualTo(String value) {
            addCriterion("facility_attach =", value, "facilityAttach");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachNotEqualTo(String value) {
            addCriterion("facility_attach <>", value, "facilityAttach");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachGreaterThan(String value) {
            addCriterion("facility_attach >", value, "facilityAttach");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachGreaterThanOrEqualTo(String value) {
            addCriterion("facility_attach >=", value, "facilityAttach");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachLessThan(String value) {
            addCriterion("facility_attach <", value, "facilityAttach");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachLessThanOrEqualTo(String value) {
            addCriterion("facility_attach <=", value, "facilityAttach");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachLike(String value) {
            addCriterion("facility_attach like", value, "facilityAttach");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachNotLike(String value) {
            addCriterion("facility_attach not like", value, "facilityAttach");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachIn(List<String> values) {
            addCriterion("facility_attach in", values, "facilityAttach");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachNotIn(List<String> values) {
            addCriterion("facility_attach not in", values, "facilityAttach");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachBetween(String value1, String value2) {
            addCriterion("facility_attach between", value1, value2, "facilityAttach");
            return (Criteria) this;
        }

        public Criteria andFacilityAttachNotBetween(String value1, String value2) {
            addCriterion("facility_attach not between", value1, value2, "facilityAttach");
            return (Criteria) this;
        }

        public Criteria andKeeperIsNull() {
            addCriterion("keeper is null");
            return (Criteria) this;
        }

        public Criteria andKeeperIsNotNull() {
            addCriterion("keeper is not null");
            return (Criteria) this;
        }

        public Criteria andKeeperEqualTo(String value) {
            addCriterion("keeper =", value, "keeper");
            return (Criteria) this;
        }

        public Criteria andKeeperNotEqualTo(String value) {
            addCriterion("keeper <>", value, "keeper");
            return (Criteria) this;
        }

        public Criteria andKeeperGreaterThan(String value) {
            addCriterion("keeper >", value, "keeper");
            return (Criteria) this;
        }

        public Criteria andKeeperGreaterThanOrEqualTo(String value) {
            addCriterion("keeper >=", value, "keeper");
            return (Criteria) this;
        }

        public Criteria andKeeperLessThan(String value) {
            addCriterion("keeper <", value, "keeper");
            return (Criteria) this;
        }

        public Criteria andKeeperLessThanOrEqualTo(String value) {
            addCriterion("keeper <=", value, "keeper");
            return (Criteria) this;
        }

        public Criteria andKeeperLike(String value) {
            addCriterion("keeper like", value, "keeper");
            return (Criteria) this;
        }

        public Criteria andKeeperNotLike(String value) {
            addCriterion("keeper not like", value, "keeper");
            return (Criteria) this;
        }

        public Criteria andKeeperIn(List<String> values) {
            addCriterion("keeper in", values, "keeper");
            return (Criteria) this;
        }

        public Criteria andKeeperNotIn(List<String> values) {
            addCriterion("keeper not in", values, "keeper");
            return (Criteria) this;
        }

        public Criteria andKeeperBetween(String value1, String value2) {
            addCriterion("keeper between", value1, value2, "keeper");
            return (Criteria) this;
        }

        public Criteria andKeeperNotBetween(String value1, String value2) {
            addCriterion("keeper not between", value1, value2, "keeper");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusIsNull() {
            addCriterion("last_test_status is null");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusIsNotNull() {
            addCriterion("last_test_status is not null");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusEqualTo(String value) {
            addCriterion("last_test_status =", value, "lastTestStatus");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusNotEqualTo(String value) {
            addCriterion("last_test_status <>", value, "lastTestStatus");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusGreaterThan(String value) {
            addCriterion("last_test_status >", value, "lastTestStatus");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusGreaterThanOrEqualTo(String value) {
            addCriterion("last_test_status >=", value, "lastTestStatus");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusLessThan(String value) {
            addCriterion("last_test_status <", value, "lastTestStatus");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusLessThanOrEqualTo(String value) {
            addCriterion("last_test_status <=", value, "lastTestStatus");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusLike(String value) {
            addCriterion("last_test_status like", value, "lastTestStatus");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusNotLike(String value) {
            addCriterion("last_test_status not like", value, "lastTestStatus");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusIn(List<String> values) {
            addCriterion("last_test_status in", values, "lastTestStatus");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusNotIn(List<String> values) {
            addCriterion("last_test_status not in", values, "lastTestStatus");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusBetween(String value1, String value2) {
            addCriterion("last_test_status between", value1, value2, "lastTestStatus");
            return (Criteria) this;
        }

        public Criteria andLastTestStatusNotBetween(String value1, String value2) {
            addCriterion("last_test_status not between", value1, value2, "lastTestStatus");
            return (Criteria) this;
        }

        public Criteria andLastTestDateIsNull() {
            addCriterion("last_test_date is null");
            return (Criteria) this;
        }

        public Criteria andLastTestDateIsNotNull() {
            addCriterion("last_test_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastTestDateEqualTo(Date value) {
            addCriterion("last_test_date =", value, "lastTestDate");
            return (Criteria) this;
        }

        public Criteria andLastTestDateNotEqualTo(Date value) {
            addCriterion("last_test_date <>", value, "lastTestDate");
            return (Criteria) this;
        }

        public Criteria andLastTestDateGreaterThan(Date value) {
            addCriterion("last_test_date >", value, "lastTestDate");
            return (Criteria) this;
        }

        public Criteria andLastTestDateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_test_date >=", value, "lastTestDate");
            return (Criteria) this;
        }

        public Criteria andLastTestDateLessThan(Date value) {
            addCriterion("last_test_date <", value, "lastTestDate");
            return (Criteria) this;
        }

        public Criteria andLastTestDateLessThanOrEqualTo(Date value) {
            addCriterion("last_test_date <=", value, "lastTestDate");
            return (Criteria) this;
        }

        public Criteria andLastTestDateIn(List<Date> values) {
            addCriterion("last_test_date in", values, "lastTestDate");
            return (Criteria) this;
        }

        public Criteria andLastTestDateNotIn(List<Date> values) {
            addCriterion("last_test_date not in", values, "lastTestDate");
            return (Criteria) this;
        }

        public Criteria andLastTestDateBetween(Date value1, Date value2) {
            addCriterion("last_test_date between", value1, value2, "lastTestDate");
            return (Criteria) this;
        }

        public Criteria andLastTestDateNotBetween(Date value1, Date value2) {
            addCriterion("last_test_date not between", value1, value2, "lastTestDate");
            return (Criteria) this;
        }

        public Criteria andLastTestResultIsNull() {
            addCriterion("last_test_result is null");
            return (Criteria) this;
        }

        public Criteria andLastTestResultIsNotNull() {
            addCriterion("last_test_result is not null");
            return (Criteria) this;
        }

        public Criteria andLastTestResultEqualTo(String value) {
            addCriterion("last_test_result =", value, "lastTestResult");
            return (Criteria) this;
        }

        public Criteria andLastTestResultNotEqualTo(String value) {
            addCriterion("last_test_result <>", value, "lastTestResult");
            return (Criteria) this;
        }

        public Criteria andLastTestResultGreaterThan(String value) {
            addCriterion("last_test_result >", value, "lastTestResult");
            return (Criteria) this;
        }

        public Criteria andLastTestResultGreaterThanOrEqualTo(String value) {
            addCriterion("last_test_result >=", value, "lastTestResult");
            return (Criteria) this;
        }

        public Criteria andLastTestResultLessThan(String value) {
            addCriterion("last_test_result <", value, "lastTestResult");
            return (Criteria) this;
        }

        public Criteria andLastTestResultLessThanOrEqualTo(String value) {
            addCriterion("last_test_result <=", value, "lastTestResult");
            return (Criteria) this;
        }

        public Criteria andLastTestResultLike(String value) {
            addCriterion("last_test_result like", value, "lastTestResult");
            return (Criteria) this;
        }

        public Criteria andLastTestResultNotLike(String value) {
            addCriterion("last_test_result not like", value, "lastTestResult");
            return (Criteria) this;
        }

        public Criteria andLastTestResultIn(List<String> values) {
            addCriterion("last_test_result in", values, "lastTestResult");
            return (Criteria) this;
        }

        public Criteria andLastTestResultNotIn(List<String> values) {
            addCriterion("last_test_result not in", values, "lastTestResult");
            return (Criteria) this;
        }

        public Criteria andLastTestResultBetween(String value1, String value2) {
            addCriterion("last_test_result between", value1, value2, "lastTestResult");
            return (Criteria) this;
        }

        public Criteria andLastTestResultNotBetween(String value1, String value2) {
            addCriterion("last_test_result not between", value1, value2, "lastTestResult");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdIsNull() {
            addCriterion("last_entrust_id is null");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdIsNotNull() {
            addCriterion("last_entrust_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdEqualTo(String value) {
            addCriterion("last_entrust_id =", value, "lastEntrustId");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdNotEqualTo(String value) {
            addCriterion("last_entrust_id <>", value, "lastEntrustId");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdGreaterThan(String value) {
            addCriterion("last_entrust_id >", value, "lastEntrustId");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdGreaterThanOrEqualTo(String value) {
            addCriterion("last_entrust_id >=", value, "lastEntrustId");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdLessThan(String value) {
            addCriterion("last_entrust_id <", value, "lastEntrustId");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdLessThanOrEqualTo(String value) {
            addCriterion("last_entrust_id <=", value, "lastEntrustId");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdLike(String value) {
            addCriterion("last_entrust_id like", value, "lastEntrustId");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdNotLike(String value) {
            addCriterion("last_entrust_id not like", value, "lastEntrustId");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdIn(List<String> values) {
            addCriterion("last_entrust_id in", values, "lastEntrustId");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdNotIn(List<String> values) {
            addCriterion("last_entrust_id not in", values, "lastEntrustId");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdBetween(String value1, String value2) {
            addCriterion("last_entrust_id between", value1, value2, "lastEntrustId");
            return (Criteria) this;
        }

        public Criteria andLastEntrustIdNotBetween(String value1, String value2) {
            addCriterion("last_entrust_id not between", value1, value2, "lastEntrustId");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdIsNull() {
            addCriterion("last_task_id is null");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdIsNotNull() {
            addCriterion("last_task_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdEqualTo(String value) {
            addCriterion("last_task_id =", value, "lastTaskId");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdNotEqualTo(String value) {
            addCriterion("last_task_id <>", value, "lastTaskId");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdGreaterThan(String value) {
            addCriterion("last_task_id >", value, "lastTaskId");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("last_task_id >=", value, "lastTaskId");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdLessThan(String value) {
            addCriterion("last_task_id <", value, "lastTaskId");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdLessThanOrEqualTo(String value) {
            addCriterion("last_task_id <=", value, "lastTaskId");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdLike(String value) {
            addCriterion("last_task_id like", value, "lastTaskId");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdNotLike(String value) {
            addCriterion("last_task_id not like", value, "lastTaskId");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdIn(List<String> values) {
            addCriterion("last_task_id in", values, "lastTaskId");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdNotIn(List<String> values) {
            addCriterion("last_task_id not in", values, "lastTaskId");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdBetween(String value1, String value2) {
            addCriterion("last_task_id between", value1, value2, "lastTaskId");
            return (Criteria) this;
        }

        public Criteria andLastTaskIdNotBetween(String value1, String value2) {
            addCriterion("last_task_id not between", value1, value2, "lastTaskId");
            return (Criteria) this;
        }

        public Criteria andLastExpectPriceIsNull() {
            addCriterion("last_expect_price is null");
            return (Criteria) this;
        }

        public Criteria andLastExpectPriceIsNotNull() {
            addCriterion("last_expect_price is not null");
            return (Criteria) this;
        }

        public Criteria andLastExpectPriceEqualTo(BigDecimal value) {
            addCriterion("last_expect_price =", value, "lastExpectPrice");
            return (Criteria) this;
        }

        public Criteria andLastExpectPriceNotEqualTo(BigDecimal value) {
            addCriterion("last_expect_price <>", value, "lastExpectPrice");
            return (Criteria) this;
        }

        public Criteria andLastExpectPriceGreaterThan(BigDecimal value) {
            addCriterion("last_expect_price >", value, "lastExpectPrice");
            return (Criteria) this;
        }

        public Criteria andLastExpectPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("last_expect_price >=", value, "lastExpectPrice");
            return (Criteria) this;
        }

        public Criteria andLastExpectPriceLessThan(BigDecimal value) {
            addCriterion("last_expect_price <", value, "lastExpectPrice");
            return (Criteria) this;
        }

        public Criteria andLastExpectPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("last_expect_price <=", value, "lastExpectPrice");
            return (Criteria) this;
        }

        public Criteria andLastExpectPriceIn(List<BigDecimal> values) {
            addCriterion("last_expect_price in", values, "lastExpectPrice");
            return (Criteria) this;
        }

        public Criteria andLastExpectPriceNotIn(List<BigDecimal> values) {
            addCriterion("last_expect_price not in", values, "lastExpectPrice");
            return (Criteria) this;
        }

        public Criteria andLastExpectPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("last_expect_price between", value1, value2, "lastExpectPrice");
            return (Criteria) this;
        }

        public Criteria andLastExpectPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("last_expect_price not between", value1, value2, "lastExpectPrice");
            return (Criteria) this;
        }

        public Criteria andLastRealPriceIsNull() {
            addCriterion("last_real_price is null");
            return (Criteria) this;
        }

        public Criteria andLastRealPriceIsNotNull() {
            addCriterion("last_real_price is not null");
            return (Criteria) this;
        }

        public Criteria andLastRealPriceEqualTo(BigDecimal value) {
            addCriterion("last_real_price =", value, "lastRealPrice");
            return (Criteria) this;
        }

        public Criteria andLastRealPriceNotEqualTo(BigDecimal value) {
            addCriterion("last_real_price <>", value, "lastRealPrice");
            return (Criteria) this;
        }

        public Criteria andLastRealPriceGreaterThan(BigDecimal value) {
            addCriterion("last_real_price >", value, "lastRealPrice");
            return (Criteria) this;
        }

        public Criteria andLastRealPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("last_real_price >=", value, "lastRealPrice");
            return (Criteria) this;
        }

        public Criteria andLastRealPriceLessThan(BigDecimal value) {
            addCriterion("last_real_price <", value, "lastRealPrice");
            return (Criteria) this;
        }

        public Criteria andLastRealPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("last_real_price <=", value, "lastRealPrice");
            return (Criteria) this;
        }

        public Criteria andLastRealPriceIn(List<BigDecimal> values) {
            addCriterion("last_real_price in", values, "lastRealPrice");
            return (Criteria) this;
        }

        public Criteria andLastRealPriceNotIn(List<BigDecimal> values) {
            addCriterion("last_real_price not in", values, "lastRealPrice");
            return (Criteria) this;
        }

        public Criteria andLastRealPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("last_real_price between", value1, value2, "lastRealPrice");
            return (Criteria) this;
        }

        public Criteria andLastRealPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("last_real_price not between", value1, value2, "lastRealPrice");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andOperaterIsNull() {
            addCriterion("operater is null");
            return (Criteria) this;
        }

        public Criteria andOperaterIsNotNull() {
            addCriterion("operater is not null");
            return (Criteria) this;
        }

        public Criteria andOperaterEqualTo(String value) {
            addCriterion("operater =", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterNotEqualTo(String value) {
            addCriterion("operater <>", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterGreaterThan(String value) {
            addCriterion("operater >", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterGreaterThanOrEqualTo(String value) {
            addCriterion("operater >=", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterLessThan(String value) {
            addCriterion("operater <", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterLessThanOrEqualTo(String value) {
            addCriterion("operater <=", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterLike(String value) {
            addCriterion("operater like", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterNotLike(String value) {
            addCriterion("operater not like", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterIn(List<String> values) {
            addCriterion("operater in", values, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterNotIn(List<String> values) {
            addCriterion("operater not in", values, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterBetween(String value1, String value2) {
            addCriterion("operater between", value1, value2, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterNotBetween(String value1, String value2) {
            addCriterion("operater not between", value1, value2, "operater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_facility
     *
     * @mbg.generated do_not_delete_during_merge Thu Feb 22 19:44:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}