package com.webside.business.mapper;

import com.webside.business.model.EnforceEntrustFacilityEntity;
import com.webside.business.model.EnforceEntrustFacilityEntityExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface EnforceEntrustFacilityEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust_facility
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    long countByExample(EnforceEntrustFacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust_facility
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    int deleteByExample(EnforceEntrustFacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust_facility
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust_facility
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    int insert(EnforceEntrustFacilityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust_facility
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    int insertSelective(EnforceEntrustFacilityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust_facility
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    List<EnforceEntrustFacilityEntity> selectByExample(EnforceEntrustFacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust_facility
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    EnforceEntrustFacilityEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust_facility
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") EnforceEntrustFacilityEntity record, @Param("example") EnforceEntrustFacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust_facility
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    int updateByExample(@Param("record") EnforceEntrustFacilityEntity record, @Param("example") EnforceEntrustFacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust_facility
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    int updateByPrimaryKeySelective(EnforceEntrustFacilityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_enforce_entrust_facility
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    int updateByPrimaryKey(EnforceEntrustFacilityEntity record);
    
    int deleteByTaskIdAndFacilityIds(Map<String, Object> parameter);
    public int deleteEntrustFacilityByIds(List<String> ids);
    

    
}