package com.webside.business.model;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.ibatis.type.Alias;

/**
 * Database Table Remarks:
 *   院收费标准表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_facility_fee
 *
 * @mbg.generated do_not_delete_during_merge Wed Dec 13 19:32:22 CST 2017
 */
@Alias("facilityFeeEntity")
public class FacilityFeeEntity {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.id
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.code
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String code;

    /**
     * Database Column Remarks:
     *   院标准ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.id_sub
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String idSub;

    /**
     * Database Column Remarks:
     *   省标准ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.id_province
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String idProvince;

    /**
     * Database Column Remarks:
     *   国家标准ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.id_country
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String idCountry;

    /**
     * Database Column Remarks:
     *   计量器具
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.name
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String name;

    /**
     * Database Column Remarks:
     *   所属专业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.field
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String field;

    /**
     * Database Column Remarks:
     *   规格型号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.model
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String model;

    /**
     * Database Column Remarks:
     *   准确度等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.accuracy
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String accuracy;

    /**
     * Database Column Remarks:
     *   测量范围
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.test_range
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String testRange;

    /**
     * Database Column Remarks:
     *   收费单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.fee_unit
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String feeUnit;

    /**
     * Database Column Remarks:
     *   收费标准
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.fee_price
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private BigDecimal feePrice;

    /**
     * Database Column Remarks:
     *   	别名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.alias
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String alias;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.status
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String status;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.status_valid
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String statusValid;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.note
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String note;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.operater
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private String operater;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.operate_time
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private Date operateTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility_fee.update_time
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.id
     *
     * @return the value of tb_facility_fee.id
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.id
     *
     * @param id the value for tb_facility_fee.id
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.code
     *
     * @return the value of tb_facility_fee.code
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.code
     *
     * @param code the value for tb_facility_fee.code
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.id_sub
     *
     * @return the value of tb_facility_fee.id_sub
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getIdSub() {
        return idSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.id_sub
     *
     * @param idSub the value for tb_facility_fee.id_sub
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setIdSub(String idSub) {
        this.idSub = idSub == null ? null : idSub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.id_province
     *
     * @return the value of tb_facility_fee.id_province
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getIdProvince() {
        return idProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.id_province
     *
     * @param idProvince the value for tb_facility_fee.id_province
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setIdProvince(String idProvince) {
        this.idProvince = idProvince == null ? null : idProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.id_country
     *
     * @return the value of tb_facility_fee.id_country
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getIdCountry() {
        return idCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.id_country
     *
     * @param idCountry the value for tb_facility_fee.id_country
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setIdCountry(String idCountry) {
        this.idCountry = idCountry == null ? null : idCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.name
     *
     * @return the value of tb_facility_fee.name
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.name
     *
     * @param name the value for tb_facility_fee.name
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.field
     *
     * @return the value of tb_facility_fee.field
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.field
     *
     * @param field the value for tb_facility_fee.field
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.model
     *
     * @return the value of tb_facility_fee.model
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.model
     *
     * @param model the value for tb_facility_fee.model
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.accuracy
     *
     * @return the value of tb_facility_fee.accuracy
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getAccuracy() {
        return accuracy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.accuracy
     *
     * @param accuracy the value for tb_facility_fee.accuracy
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setAccuracy(String accuracy) {
        this.accuracy = accuracy == null ? null : accuracy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.test_range
     *
     * @return the value of tb_facility_fee.test_range
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getTestRange() {
        return testRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.test_range
     *
     * @param testRange the value for tb_facility_fee.test_range
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setTestRange(String testRange) {
        this.testRange = testRange == null ? null : testRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.fee_unit
     *
     * @return the value of tb_facility_fee.fee_unit
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getFeeUnit() {
        return feeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.fee_unit
     *
     * @param feeUnit the value for tb_facility_fee.fee_unit
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setFeeUnit(String feeUnit) {
        this.feeUnit = feeUnit == null ? null : feeUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.fee_price
     *
     * @return the value of tb_facility_fee.fee_price
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public BigDecimal getFeePrice() {
        return feePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.fee_price
     *
     * @param feePrice the value for tb_facility_fee.fee_price
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setFeePrice(BigDecimal feePrice) {
        this.feePrice = feePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.alias
     *
     * @return the value of tb_facility_fee.alias
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.alias
     *
     * @param alias the value for tb_facility_fee.alias
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.status
     *
     * @return the value of tb_facility_fee.status
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.status
     *
     * @param status the value for tb_facility_fee.status
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.status_valid
     *
     * @return the value of tb_facility_fee.status_valid
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getStatusValid() {
        return statusValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.status_valid
     *
     * @param statusValid the value for tb_facility_fee.status_valid
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setStatusValid(String statusValid) {
        this.statusValid = statusValid == null ? null : statusValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.note
     *
     * @return the value of tb_facility_fee.note
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.note
     *
     * @param note the value for tb_facility_fee.note
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.operater
     *
     * @return the value of tb_facility_fee.operater
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getOperater() {
        return operater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.operater
     *
     * @param operater the value for tb_facility_fee.operater
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setOperater(String operater) {
        this.operater = operater == null ? null : operater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.operate_time
     *
     * @return the value of tb_facility_fee.operate_time
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.operate_time
     *
     * @param operateTime the value for tb_facility_fee.operate_time
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility_fee.update_time
     *
     * @return the value of tb_facility_fee.update_time
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility_fee.update_time
     *
     * @param updateTime the value for tb_facility_fee.update_time
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}