package com.webside.business.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   ä»»åŠ¡ä»ªå™¨æ˜Žç»†è¡¨
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_task_facility
 *
 * @mbg.generated do_not_delete_during_merge Fri Jan 19 23:37:15 CST 2018
 */
public class TaskFacilityEntity {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task_facility.id
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    private String id;

    /**
     * Database Column Remarks:
     *   ä»»åŠ¡id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task_facility.task_id
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    private String taskId;

    /**
     * Database Column Remarks:
     *   ä»ªå™¨id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task_facility.facility_id
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    private String facilityId;

    /**
     * Database Column Remarks:
     *   æ›´æ–°æ—¶é—´
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task_facility.update_time
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_facility.id
     *
     * @return the value of tb_task_facility.id
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_facility.id
     *
     * @param id the value for tb_task_facility.id
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_facility.task_id
     *
     * @return the value of tb_task_facility.task_id
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_facility.task_id
     *
     * @param taskId the value for tb_task_facility.task_id
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_facility.facility_id
     *
     * @return the value of tb_task_facility.facility_id
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    public String getFacilityId() {
        return facilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_facility.facility_id
     *
     * @param facilityId the value for tb_task_facility.facility_id
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    public void setFacilityId(String facilityId) {
        this.facilityId = facilityId == null ? null : facilityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_facility.update_time
     *
     * @return the value of tb_task_facility.update_time
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_facility.update_time
     *
     * @param updateTime the value for tb_task_facility.update_time
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}