package com.webside.business.model;

import java.io.Serializable;

import org.apache.ibatis.type.Alias;

/**
 * Database Table Remarks:
 *   打印模板存储
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_company_auth
 *
 * @mbg.generated do_not_delete_during_merge Sat Dec 16 06:27:51 CST 2017
 */
@Alias("PropertyEntity")
public class PropertyEntity  implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1258474049985166421L;

	private String id;
	private String content;
	private String note;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
    
}