package com.webside.business.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.webside.base.basemapper.BaseMapper;
import com.webside.business.model.FacilityEntity;
import com.webside.business.model.FacilityEntityExample;

@Repository
public interface FacilityEntityMapper extends BaseMapper<FacilityEntity, String>{
	  /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Dec 14 15:13:01 CST 2017
     */
    long countByExample(FacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Dec 14 15:13:01 CST 2017
     */
    int deleteByExample(FacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Dec 14 15:13:01 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Dec 14 15:13:01 CST 2017
     */
    int insert(FacilityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Dec 14 15:13:01 CST 2017
     */
    int insertSelective(FacilityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Dec 14 15:13:01 CST 2017
     */
    List<FacilityEntity> selectByExample(FacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Dec 14 15:13:01 CST 2017
     */
    FacilityEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Dec 14 15:13:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") FacilityEntity record, @Param("example") FacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Dec 14 15:13:01 CST 2017
     */
    int updateByExample(@Param("record") FacilityEntity record, @Param("example") FacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Dec 14 15:13:01 CST 2017
     */
    int updateByPrimaryKeySelective(FacilityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility
     *
     * @mbg.generated Thu Dec 14 15:13:01 CST 2017
     */
    int updateByPrimaryKey(FacilityEntity record);
    
    public int deleteBatchByIds(List<String> ids);
    
    public int updateFacilityStateById(FacilityEntity record);
    
    int insertBatch(List<FacilityEntity> list);

	List<String> selectFactoryId(Map<String, Object> parameter);
	List<FacilityEntity> queryInquriyListByPage(Map<String, Object> parameter);
}