package com.webside.business.mapper;

import com.webside.business.model.TaskEntity;
import com.webside.business.model.TaskFacilityEntity;
import com.webside.business.model.TaskFacilityEntityExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TaskFacilityEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_facility
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    long countByExample(TaskFacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_facility
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    int deleteByExample(TaskFacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_facility
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_facility
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    int insert(TaskFacilityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_facility
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    int insertSelective(TaskFacilityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_facility
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    List<TaskFacilityEntity> selectByExample(TaskFacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_facility
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    TaskFacilityEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_facility
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaskFacilityEntity record, @Param("example") TaskFacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_facility
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    int updateByExample(@Param("record") TaskFacilityEntity record, @Param("example") TaskFacilityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_facility
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    int updateByPrimaryKeySelective(TaskFacilityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_facility
     *
     * @mbg.generated Fri Jan 19 23:37:15 CST 2018
     */
    int updateByPrimaryKey(TaskFacilityEntity record);
    
    public List<TaskFacilityEntity> queryListByPage(Map<String, Object> parameter);
}