package com.webside.business.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   è¯¢ä»·è¡¨
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_inquiry
 *
 * @mbg.generated do_not_delete_during_merge Sat Jan 06 21:07:14 CST 2018
 */
public class InquiryEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_inquiry.id
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    private String id;

    /**
     * Database Column Remarks:
     *   ç”¨æˆ·Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_inquiry.user_id
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    private Long userId;
    

    private Long replyUserId;
    
  //显示用不存储
    private String userName;
    
  //显示用不存储
    private String replyUserName;

    /**
     * Database Column Remarks:
     *   è¯¢ä»·å…¬å�¸
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_inquiry.company_id
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    private Long companyId;
    

    //显示用不存储
    private String companyName;

    /**
     * Database Column Remarks:
     *   è¯¢ä»·çŠ¶æ€�
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_inquiry.status
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   æ¸…å�•ç‰ˆæœ¬
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_inquiry.active_version
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    private Integer activeVersion;

    /**
     * Database Column Remarks:
     *   å¤‡æ³¨
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_inquiry.note
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    private String note;

    /**
     * Database Column Remarks:
     *   åˆ›å»ºæ—¶é—´
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_inquiry.create_time
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   æ›´æ–°æ—¶é—´
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_inquiry.update_time
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_inquiry.id
     *
     * @return the value of tb_inquiry.id
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_inquiry.id
     *
     * @param id the value for tb_inquiry.id
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_inquiry.user_id
     *
     * @return the value of tb_inquiry.user_id
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_inquiry.user_id
     *
     * @param userId the value for tb_inquiry.user_id
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_inquiry.company_id
     *
     * @return the value of tb_inquiry.company_id
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_inquiry.company_id
     *
     * @param companyId the value for tb_inquiry.company_id
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_inquiry.status
     *
     * @return the value of tb_inquiry.status
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_inquiry.status
     *
     * @param status the value for tb_inquiry.status
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_inquiry.active_version
     *
     * @return the value of tb_inquiry.active_version
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public Integer getActiveVersion() {
        return activeVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_inquiry.active_version
     *
     * @param activeVersion the value for tb_inquiry.active_version
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public void setActiveVersion(Integer activeVersion) {
        this.activeVersion = activeVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_inquiry.note
     *
     * @return the value of tb_inquiry.note
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_inquiry.note
     *
     * @param note the value for tb_inquiry.note
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_inquiry.create_time
     *
     * @return the value of tb_inquiry.create_time
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_inquiry.create_time
     *
     * @param createTime the value for tb_inquiry.create_time
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_inquiry.update_time
     *
     * @return the value of tb_inquiry.update_time
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_inquiry.update_time
     *
     * @param updateTime the value for tb_inquiry.update_time
     *
     * @mbg.generated Sat Jan 06 21:07:14 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public Long getReplyUserId() {
		return replyUserId;
	}

	public void setReplyUserId(Long replyUserId) {
		this.replyUserId = replyUserId;
	}

	public String getReplyUserName() {
		return replyUserName;
	}

	public void setReplyUserName(String replyUserName) {
		this.replyUserName = replyUserName;
	}
}