package com.webside.business.model;

import java.util.Date;

import org.apache.ibatis.type.Alias;

/**
 * Database Table Remarks:
 *   检测机构表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_examine_organ
 *
 * @mbg.generated do_not_delete_during_merge Sat Dec 16 06:27:51 CST 2017
 */
@Alias("examineOrganEntity")
public class ExamineOrganEntity {
    /**
     * Database Column Remarks:
     *   机构id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.id
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.name
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String name;

    /**
     * Database Column Remarks:
     *   电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.telephone
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.contact_person
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String contactPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.mobile
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.fax
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String fax;

    /**
     * Database Column Remarks:
     *   住址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.address
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.region_code
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String regionCode;

    /**
     * Database Column Remarks:
     *   开户银行
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.bank
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String bank;

    /**
     * Database Column Remarks:
     *   账户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.account_name
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String accountName;

    /**
     * Database Column Remarks:
     *   银行账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.account_code
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String accountCode;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.status
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String status;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.note
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String note;
    
    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.creator_name
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private String creatorName;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.create_time
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_examine_organ.update_time
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.id
     *
     * @return the value of tb_examine_organ.id
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.id
     *
     * @param id the value for tb_examine_organ.id
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.name
     *
     * @return the value of tb_examine_organ.name
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.name
     *
     * @param name the value for tb_examine_organ.name
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.telephone
     *
     * @return the value of tb_examine_organ.telephone
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.telephone
     *
     * @param telephone the value for tb_examine_organ.telephone
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.contact_person
     *
     * @return the value of tb_examine_organ.contact_person
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.contact_person
     *
     * @param contactPerson the value for tb_examine_organ.contact_person
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.mobile
     *
     * @return the value of tb_examine_organ.mobile
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.mobile
     *
     * @param mobile the value for tb_examine_organ.mobile
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.fax
     *
     * @return the value of tb_examine_organ.fax
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.fax
     *
     * @param fax the value for tb_examine_organ.fax
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.address
     *
     * @return the value of tb_examine_organ.address
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.address
     *
     * @param address the value for tb_examine_organ.address
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.region_code
     *
     * @return the value of tb_examine_organ.region_code
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.region_code
     *
     * @param regionCode the value for tb_examine_organ.region_code
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.bank
     *
     * @return the value of tb_examine_organ.bank
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.bank
     *
     * @param bank the value for tb_examine_organ.bank
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.account_name
     *
     * @return the value of tb_examine_organ.account_name
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.account_name
     *
     * @param accountName the value for tb_examine_organ.account_name
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.account_code
     *
     * @return the value of tb_examine_organ.account_code
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.account_code
     *
     * @param accountCode the value for tb_examine_organ.account_code
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.status
     *
     * @return the value of tb_examine_organ.status
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.status
     *
     * @param status the value for tb_examine_organ.status
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.creator_name
     *
     * @return the value of tb_examine_organ.creator_name
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.creator_name
     *
     * @param creatorName the value for tb_examine_organ.creator_name
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.create_time
     *
     * @return the value of tb_examine_organ.create_time
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.create_time
     *
     * @param createTime the value for tb_examine_organ.create_time
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_examine_organ.update_time
     *
     * @return the value of tb_examine_organ.update_time
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_examine_organ.update_time
     *
     * @param updateTime the value for tb_examine_organ.update_time
     *
     * @mbg.generated Sat Dec 16 06:27:51 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}
}