package com.webside.business.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FacilityFeeEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public FacilityFeeEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andIdSubIsNull() {
            addCriterion("id_sub is null");
            return (Criteria) this;
        }

        public Criteria andIdSubIsNotNull() {
            addCriterion("id_sub is not null");
            return (Criteria) this;
        }

        public Criteria andIdSubEqualTo(String value) {
            addCriterion("id_sub =", value, "idSub");
            return (Criteria) this;
        }

        public Criteria andIdSubNotEqualTo(String value) {
            addCriterion("id_sub <>", value, "idSub");
            return (Criteria) this;
        }

        public Criteria andIdSubGreaterThan(String value) {
            addCriterion("id_sub >", value, "idSub");
            return (Criteria) this;
        }

        public Criteria andIdSubGreaterThanOrEqualTo(String value) {
            addCriterion("id_sub >=", value, "idSub");
            return (Criteria) this;
        }

        public Criteria andIdSubLessThan(String value) {
            addCriterion("id_sub <", value, "idSub");
            return (Criteria) this;
        }

        public Criteria andIdSubLessThanOrEqualTo(String value) {
            addCriterion("id_sub <=", value, "idSub");
            return (Criteria) this;
        }

        public Criteria andIdSubLike(String value) {
            addCriterion("id_sub like", value, "idSub");
            return (Criteria) this;
        }

        public Criteria andIdSubNotLike(String value) {
            addCriterion("id_sub not like", value, "idSub");
            return (Criteria) this;
        }

        public Criteria andIdSubIn(List<String> values) {
            addCriterion("id_sub in", values, "idSub");
            return (Criteria) this;
        }

        public Criteria andIdSubNotIn(List<String> values) {
            addCriterion("id_sub not in", values, "idSub");
            return (Criteria) this;
        }

        public Criteria andIdSubBetween(String value1, String value2) {
            addCriterion("id_sub between", value1, value2, "idSub");
            return (Criteria) this;
        }

        public Criteria andIdSubNotBetween(String value1, String value2) {
            addCriterion("id_sub not between", value1, value2, "idSub");
            return (Criteria) this;
        }

        public Criteria andIdProvinceIsNull() {
            addCriterion("id_province is null");
            return (Criteria) this;
        }

        public Criteria andIdProvinceIsNotNull() {
            addCriterion("id_province is not null");
            return (Criteria) this;
        }

        public Criteria andIdProvinceEqualTo(String value) {
            addCriterion("id_province =", value, "idProvince");
            return (Criteria) this;
        }

        public Criteria andIdProvinceNotEqualTo(String value) {
            addCriterion("id_province <>", value, "idProvince");
            return (Criteria) this;
        }

        public Criteria andIdProvinceGreaterThan(String value) {
            addCriterion("id_province >", value, "idProvince");
            return (Criteria) this;
        }

        public Criteria andIdProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("id_province >=", value, "idProvince");
            return (Criteria) this;
        }

        public Criteria andIdProvinceLessThan(String value) {
            addCriterion("id_province <", value, "idProvince");
            return (Criteria) this;
        }

        public Criteria andIdProvinceLessThanOrEqualTo(String value) {
            addCriterion("id_province <=", value, "idProvince");
            return (Criteria) this;
        }

        public Criteria andIdProvinceLike(String value) {
            addCriterion("id_province like", value, "idProvince");
            return (Criteria) this;
        }

        public Criteria andIdProvinceNotLike(String value) {
            addCriterion("id_province not like", value, "idProvince");
            return (Criteria) this;
        }

        public Criteria andIdProvinceIn(List<String> values) {
            addCriterion("id_province in", values, "idProvince");
            return (Criteria) this;
        }

        public Criteria andIdProvinceNotIn(List<String> values) {
            addCriterion("id_province not in", values, "idProvince");
            return (Criteria) this;
        }

        public Criteria andIdProvinceBetween(String value1, String value2) {
            addCriterion("id_province between", value1, value2, "idProvince");
            return (Criteria) this;
        }

        public Criteria andIdProvinceNotBetween(String value1, String value2) {
            addCriterion("id_province not between", value1, value2, "idProvince");
            return (Criteria) this;
        }

        public Criteria andIdCountryIsNull() {
            addCriterion("id_country is null");
            return (Criteria) this;
        }

        public Criteria andIdCountryIsNotNull() {
            addCriterion("id_country is not null");
            return (Criteria) this;
        }

        public Criteria andIdCountryEqualTo(String value) {
            addCriterion("id_country =", value, "idCountry");
            return (Criteria) this;
        }

        public Criteria andIdCountryNotEqualTo(String value) {
            addCriterion("id_country <>", value, "idCountry");
            return (Criteria) this;
        }

        public Criteria andIdCountryGreaterThan(String value) {
            addCriterion("id_country >", value, "idCountry");
            return (Criteria) this;
        }

        public Criteria andIdCountryGreaterThanOrEqualTo(String value) {
            addCriterion("id_country >=", value, "idCountry");
            return (Criteria) this;
        }

        public Criteria andIdCountryLessThan(String value) {
            addCriterion("id_country <", value, "idCountry");
            return (Criteria) this;
        }

        public Criteria andIdCountryLessThanOrEqualTo(String value) {
            addCriterion("id_country <=", value, "idCountry");
            return (Criteria) this;
        }

        public Criteria andIdCountryLike(String value) {
            addCriterion("id_country like", value, "idCountry");
            return (Criteria) this;
        }

        public Criteria andIdCountryNotLike(String value) {
            addCriterion("id_country not like", value, "idCountry");
            return (Criteria) this;
        }

        public Criteria andIdCountryIn(List<String> values) {
            addCriterion("id_country in", values, "idCountry");
            return (Criteria) this;
        }

        public Criteria andIdCountryNotIn(List<String> values) {
            addCriterion("id_country not in", values, "idCountry");
            return (Criteria) this;
        }

        public Criteria andIdCountryBetween(String value1, String value2) {
            addCriterion("id_country between", value1, value2, "idCountry");
            return (Criteria) this;
        }

        public Criteria andIdCountryNotBetween(String value1, String value2) {
            addCriterion("id_country not between", value1, value2, "idCountry");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andFieldIsNull() {
            addCriterion("field is null");
            return (Criteria) this;
        }

        public Criteria andFieldIsNotNull() {
            addCriterion("field is not null");
            return (Criteria) this;
        }

        public Criteria andFieldEqualTo(String value) {
            addCriterion("field =", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldNotEqualTo(String value) {
            addCriterion("field <>", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldGreaterThan(String value) {
            addCriterion("field >", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldGreaterThanOrEqualTo(String value) {
            addCriterion("field >=", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldLessThan(String value) {
            addCriterion("field <", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldLessThanOrEqualTo(String value) {
            addCriterion("field <=", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldLike(String value) {
            addCriterion("field like", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldNotLike(String value) {
            addCriterion("field not like", value, "field");
            return (Criteria) this;
        }

        public Criteria andFieldIn(List<String> values) {
            addCriterion("field in", values, "field");
            return (Criteria) this;
        }

        public Criteria andFieldNotIn(List<String> values) {
            addCriterion("field not in", values, "field");
            return (Criteria) this;
        }

        public Criteria andFieldBetween(String value1, String value2) {
            addCriterion("field between", value1, value2, "field");
            return (Criteria) this;
        }

        public Criteria andFieldNotBetween(String value1, String value2) {
            addCriterion("field not between", value1, value2, "field");
            return (Criteria) this;
        }

        public Criteria andModelIsNull() {
            addCriterion("model is null");
            return (Criteria) this;
        }

        public Criteria andModelIsNotNull() {
            addCriterion("model is not null");
            return (Criteria) this;
        }

        public Criteria andModelEqualTo(String value) {
            addCriterion("model =", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotEqualTo(String value) {
            addCriterion("model <>", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThan(String value) {
            addCriterion("model >", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThanOrEqualTo(String value) {
            addCriterion("model >=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThan(String value) {
            addCriterion("model <", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThanOrEqualTo(String value) {
            addCriterion("model <=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLike(String value) {
            addCriterion("model like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotLike(String value) {
            addCriterion("model not like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelIn(List<String> values) {
            addCriterion("model in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotIn(List<String> values) {
            addCriterion("model not in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelBetween(String value1, String value2) {
            addCriterion("model between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotBetween(String value1, String value2) {
            addCriterion("model not between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andAccuracyIsNull() {
            addCriterion("accuracy is null");
            return (Criteria) this;
        }

        public Criteria andAccuracyIsNotNull() {
            addCriterion("accuracy is not null");
            return (Criteria) this;
        }

        public Criteria andAccuracyEqualTo(String value) {
            addCriterion("accuracy =", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyNotEqualTo(String value) {
            addCriterion("accuracy <>", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyGreaterThan(String value) {
            addCriterion("accuracy >", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyGreaterThanOrEqualTo(String value) {
            addCriterion("accuracy >=", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyLessThan(String value) {
            addCriterion("accuracy <", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyLessThanOrEqualTo(String value) {
            addCriterion("accuracy <=", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyLike(String value) {
            addCriterion("accuracy like", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyNotLike(String value) {
            addCriterion("accuracy not like", value, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyIn(List<String> values) {
            addCriterion("accuracy in", values, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyNotIn(List<String> values) {
            addCriterion("accuracy not in", values, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyBetween(String value1, String value2) {
            addCriterion("accuracy between", value1, value2, "accuracy");
            return (Criteria) this;
        }

        public Criteria andAccuracyNotBetween(String value1, String value2) {
            addCriterion("accuracy not between", value1, value2, "accuracy");
            return (Criteria) this;
        }

        public Criteria andTestRangeIsNull() {
            addCriterion("test_range is null");
            return (Criteria) this;
        }

        public Criteria andTestRangeIsNotNull() {
            addCriterion("test_range is not null");
            return (Criteria) this;
        }

        public Criteria andTestRangeEqualTo(String value) {
            addCriterion("test_range =", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeNotEqualTo(String value) {
            addCriterion("test_range <>", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeGreaterThan(String value) {
            addCriterion("test_range >", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeGreaterThanOrEqualTo(String value) {
            addCriterion("test_range >=", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeLessThan(String value) {
            addCriterion("test_range <", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeLessThanOrEqualTo(String value) {
            addCriterion("test_range <=", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeLike(String value) {
            addCriterion("test_range like", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeNotLike(String value) {
            addCriterion("test_range not like", value, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeIn(List<String> values) {
            addCriterion("test_range in", values, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeNotIn(List<String> values) {
            addCriterion("test_range not in", values, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeBetween(String value1, String value2) {
            addCriterion("test_range between", value1, value2, "testRange");
            return (Criteria) this;
        }

        public Criteria andTestRangeNotBetween(String value1, String value2) {
            addCriterion("test_range not between", value1, value2, "testRange");
            return (Criteria) this;
        }

        public Criteria andFeeUnitIsNull() {
            addCriterion("fee_unit is null");
            return (Criteria) this;
        }

        public Criteria andFeeUnitIsNotNull() {
            addCriterion("fee_unit is not null");
            return (Criteria) this;
        }

        public Criteria andFeeUnitEqualTo(String value) {
            addCriterion("fee_unit =", value, "feeUnit");
            return (Criteria) this;
        }

        public Criteria andFeeUnitNotEqualTo(String value) {
            addCriterion("fee_unit <>", value, "feeUnit");
            return (Criteria) this;
        }

        public Criteria andFeeUnitGreaterThan(String value) {
            addCriterion("fee_unit >", value, "feeUnit");
            return (Criteria) this;
        }

        public Criteria andFeeUnitGreaterThanOrEqualTo(String value) {
            addCriterion("fee_unit >=", value, "feeUnit");
            return (Criteria) this;
        }

        public Criteria andFeeUnitLessThan(String value) {
            addCriterion("fee_unit <", value, "feeUnit");
            return (Criteria) this;
        }

        public Criteria andFeeUnitLessThanOrEqualTo(String value) {
            addCriterion("fee_unit <=", value, "feeUnit");
            return (Criteria) this;
        }

        public Criteria andFeeUnitLike(String value) {
            addCriterion("fee_unit like", value, "feeUnit");
            return (Criteria) this;
        }

        public Criteria andFeeUnitNotLike(String value) {
            addCriterion("fee_unit not like", value, "feeUnit");
            return (Criteria) this;
        }

        public Criteria andFeeUnitIn(List<String> values) {
            addCriterion("fee_unit in", values, "feeUnit");
            return (Criteria) this;
        }

        public Criteria andFeeUnitNotIn(List<String> values) {
            addCriterion("fee_unit not in", values, "feeUnit");
            return (Criteria) this;
        }

        public Criteria andFeeUnitBetween(String value1, String value2) {
            addCriterion("fee_unit between", value1, value2, "feeUnit");
            return (Criteria) this;
        }

        public Criteria andFeeUnitNotBetween(String value1, String value2) {
            addCriterion("fee_unit not between", value1, value2, "feeUnit");
            return (Criteria) this;
        }

        public Criteria andFeePriceIsNull() {
            addCriterion("fee_price is null");
            return (Criteria) this;
        }

        public Criteria andFeePriceIsNotNull() {
            addCriterion("fee_price is not null");
            return (Criteria) this;
        }

        public Criteria andFeePriceEqualTo(BigDecimal value) {
            addCriterion("fee_price =", value, "feePrice");
            return (Criteria) this;
        }

        public Criteria andFeePriceNotEqualTo(BigDecimal value) {
            addCriterion("fee_price <>", value, "feePrice");
            return (Criteria) this;
        }

        public Criteria andFeePriceGreaterThan(BigDecimal value) {
            addCriterion("fee_price >", value, "feePrice");
            return (Criteria) this;
        }

        public Criteria andFeePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fee_price >=", value, "feePrice");
            return (Criteria) this;
        }

        public Criteria andFeePriceLessThan(BigDecimal value) {
            addCriterion("fee_price <", value, "feePrice");
            return (Criteria) this;
        }

        public Criteria andFeePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fee_price <=", value, "feePrice");
            return (Criteria) this;
        }

        public Criteria andFeePriceIn(List<BigDecimal> values) {
            addCriterion("fee_price in", values, "feePrice");
            return (Criteria) this;
        }

        public Criteria andFeePriceNotIn(List<BigDecimal> values) {
            addCriterion("fee_price not in", values, "feePrice");
            return (Criteria) this;
        }

        public Criteria andFeePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fee_price between", value1, value2, "feePrice");
            return (Criteria) this;
        }

        public Criteria andFeePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fee_price not between", value1, value2, "feePrice");
            return (Criteria) this;
        }

        public Criteria andAliasIsNull() {
            addCriterion("alias is null");
            return (Criteria) this;
        }

        public Criteria andAliasIsNotNull() {
            addCriterion("alias is not null");
            return (Criteria) this;
        }

        public Criteria andAliasEqualTo(String value) {
            addCriterion("alias =", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotEqualTo(String value) {
            addCriterion("alias <>", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThan(String value) {
            addCriterion("alias >", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThanOrEqualTo(String value) {
            addCriterion("alias >=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThan(String value) {
            addCriterion("alias <", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThanOrEqualTo(String value) {
            addCriterion("alias <=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLike(String value) {
            addCriterion("alias like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotLike(String value) {
            addCriterion("alias not like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasIn(List<String> values) {
            addCriterion("alias in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotIn(List<String> values) {
            addCriterion("alias not in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasBetween(String value1, String value2) {
            addCriterion("alias between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotBetween(String value1, String value2) {
            addCriterion("alias not between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusValidIsNull() {
            addCriterion("status_valid is null");
            return (Criteria) this;
        }

        public Criteria andStatusValidIsNotNull() {
            addCriterion("status_valid is not null");
            return (Criteria) this;
        }

        public Criteria andStatusValidEqualTo(String value) {
            addCriterion("status_valid =", value, "statusValid");
            return (Criteria) this;
        }

        public Criteria andStatusValidNotEqualTo(String value) {
            addCriterion("status_valid <>", value, "statusValid");
            return (Criteria) this;
        }

        public Criteria andStatusValidGreaterThan(String value) {
            addCriterion("status_valid >", value, "statusValid");
            return (Criteria) this;
        }

        public Criteria andStatusValidGreaterThanOrEqualTo(String value) {
            addCriterion("status_valid >=", value, "statusValid");
            return (Criteria) this;
        }

        public Criteria andStatusValidLessThan(String value) {
            addCriterion("status_valid <", value, "statusValid");
            return (Criteria) this;
        }

        public Criteria andStatusValidLessThanOrEqualTo(String value) {
            addCriterion("status_valid <=", value, "statusValid");
            return (Criteria) this;
        }

        public Criteria andStatusValidLike(String value) {
            addCriterion("status_valid like", value, "statusValid");
            return (Criteria) this;
        }

        public Criteria andStatusValidNotLike(String value) {
            addCriterion("status_valid not like", value, "statusValid");
            return (Criteria) this;
        }

        public Criteria andStatusValidIn(List<String> values) {
            addCriterion("status_valid in", values, "statusValid");
            return (Criteria) this;
        }

        public Criteria andStatusValidNotIn(List<String> values) {
            addCriterion("status_valid not in", values, "statusValid");
            return (Criteria) this;
        }

        public Criteria andStatusValidBetween(String value1, String value2) {
            addCriterion("status_valid between", value1, value2, "statusValid");
            return (Criteria) this;
        }

        public Criteria andStatusValidNotBetween(String value1, String value2) {
            addCriterion("status_valid not between", value1, value2, "statusValid");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andOperaterIsNull() {
            addCriterion("operater is null");
            return (Criteria) this;
        }

        public Criteria andOperaterIsNotNull() {
            addCriterion("operater is not null");
            return (Criteria) this;
        }

        public Criteria andOperaterEqualTo(String value) {
            addCriterion("operater =", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterNotEqualTo(String value) {
            addCriterion("operater <>", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterGreaterThan(String value) {
            addCriterion("operater >", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterGreaterThanOrEqualTo(String value) {
            addCriterion("operater >=", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterLessThan(String value) {
            addCriterion("operater <", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterLessThanOrEqualTo(String value) {
            addCriterion("operater <=", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterLike(String value) {
            addCriterion("operater like", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterNotLike(String value) {
            addCriterion("operater not like", value, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterIn(List<String> values) {
            addCriterion("operater in", values, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterNotIn(List<String> values) {
            addCriterion("operater not in", values, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterBetween(String value1, String value2) {
            addCriterion("operater between", value1, value2, "operater");
            return (Criteria) this;
        }

        public Criteria andOperaterNotBetween(String value1, String value2) {
            addCriterion("operater not between", value1, value2, "operater");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNull() {
            addCriterion("operate_time is null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNotNull() {
            addCriterion("operate_time is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeEqualTo(Date value) {
            addCriterion("operate_time =", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotEqualTo(Date value) {
            addCriterion("operate_time <>", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThan(Date value) {
            addCriterion("operate_time >", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("operate_time >=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThan(Date value) {
            addCriterion("operate_time <", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThanOrEqualTo(Date value) {
            addCriterion("operate_time <=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIn(List<Date> values) {
            addCriterion("operate_time in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotIn(List<Date> values) {
            addCriterion("operate_time not in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeBetween(Date value1, Date value2) {
            addCriterion("operate_time between", value1, value2, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotBetween(Date value1, Date value2) {
            addCriterion("operate_time not between", value1, value2, "operateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_facility_fee
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 13 19:32:22 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_facility_fee
     *
     * @mbg.generated Wed Dec 13 19:32:22 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}