package com.webside.business.model;

import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   å¼ºæ£€å§”æ‰˜å�•æ˜Žç»†
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_enforce_entrust_facility
 *
 * @mbg.generated do_not_delete_during_merge Sun Jan 28 22:53:29 CST 2018
 */
public class EnforceEntrustFacilityEntity {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust_facility.id
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    private String id;

    /**
     * Database Column Remarks:
     *   ä»»åŠ¡å�•id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust_facility.task_id
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    private String taskId;

    /**
     * Database Column Remarks:
     *   å§”æ‰˜å�•id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust_facility.entrust_id
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    private String entrustId;

    /**
     * Database Column Remarks:
     *   ä¼�ä¸šid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust_facility.cid
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    private Integer cid;

    /**
     * Database Column Remarks:
     *   ä»ªå™¨id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust_facility.facility_id
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    private String facilityId;

    /**
     * Database Column Remarks:
     *   æŠ¥ä»·
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust_facility.expect_price
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    private BigDecimal expectPrice;

    /**
     * Database Column Remarks:
     *   æ˜¯å�¦å�ˆæ ¼ 1å�ˆæ ¼ 0ä¸�å�ˆæ ¼
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust_facility.test_result
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    private String testResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust_facility.id
     *
     * @return the value of tb_enforce_entrust_facility.id
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust_facility.id
     *
     * @param id the value for tb_enforce_entrust_facility.id
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust_facility.task_id
     *
     * @return the value of tb_enforce_entrust_facility.task_id
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust_facility.task_id
     *
     * @param taskId the value for tb_enforce_entrust_facility.task_id
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust_facility.entrust_id
     *
     * @return the value of tb_enforce_entrust_facility.entrust_id
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public String getEntrustId() {
        return entrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust_facility.entrust_id
     *
     * @param entrustId the value for tb_enforce_entrust_facility.entrust_id
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public void setEntrustId(String entrustId) {
        this.entrustId = entrustId == null ? null : entrustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust_facility.cid
     *
     * @return the value of tb_enforce_entrust_facility.cid
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust_facility.cid
     *
     * @param cid the value for tb_enforce_entrust_facility.cid
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust_facility.facility_id
     *
     * @return the value of tb_enforce_entrust_facility.facility_id
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public String getFacilityId() {
        return facilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust_facility.facility_id
     *
     * @param facilityId the value for tb_enforce_entrust_facility.facility_id
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public void setFacilityId(String facilityId) {
        this.facilityId = facilityId == null ? null : facilityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust_facility.expect_price
     *
     * @return the value of tb_enforce_entrust_facility.expect_price
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public BigDecimal getExpectPrice() {
        return expectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust_facility.expect_price
     *
     * @param expectPrice the value for tb_enforce_entrust_facility.expect_price
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public void setExpectPrice(BigDecimal expectPrice) {
        this.expectPrice = expectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust_facility.test_result
     *
     * @return the value of tb_enforce_entrust_facility.test_result
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public String getTestResult() {
        return testResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust_facility.test_result
     *
     * @param testResult the value for tb_enforce_entrust_facility.test_result
     *
     * @mbg.generated Sun Jan 28 22:53:29 CST 2018
     */
    public void setTestResult(String testResult) {
        this.testResult = testResult == null ? null : testResult.trim();
    }
}