package com.webside.business.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   å™¨å…·è¡¨
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_facility
 *
 * @mbg.generated do_not_delete_during_merge Thu Feb 22 19:44:41 CST 2018
 */
public class FacilityEntity {
    /**
     * Database Column Remarks:
     *   ï¿½ï¿½ï¿½ï¿½ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.id
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String id;

    /**
     * Database Column Remarks:
     *   ä¼�ä¸šiD
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.cid
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private Integer cid;

    /**
     * Database Column Remarks:
     *   å‡ºåŽ‚ç¼–å�·
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.factory_no
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String factoryNo;

    /**
     * Database Column Remarks:
     *   ä»ªå™¨å��ç§°
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.facility_name
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String facilityName;

    /**
     * Database Column Remarks:
     *   ä»ªå™¨ç±»åž‹
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.facility_type
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String facilityType;

    /**
     * Database Column Remarks:
     *   è§„æ ¼åž‹å�·
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.model
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String model;

    /**
     * Database Column Remarks:
     *   å‡†ç¡®åº¦ç­‰çº§
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.accuracy
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String accuracy;

    /**
     * Database Column Remarks:
     *   æµ‹é‡�èŒƒå›´
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.test_range
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String testRange;

    /**
     * Database Column Remarks:
     *   è´£ä»»éƒ¨é—¨
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.belong_organ
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String belongOrgan;

    /**
     * Database Column Remarks:
     *   ç®¡ç�†ç¼–å�·
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.manage_no
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String manageNo;

    /**
     * Database Column Remarks:
     *   ç”Ÿäº§åŽ‚å®¶
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.manufacturer
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String manufacturer;

    /**
     * Database Column Remarks:
     *   å®‰è£…/ä½¿ç”¨åœ°ç‚¹
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.use_place
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String usePlace;

    /**
     * Database Column Remarks:
     *   è®¡é‡�å™¨å…·ç”¨é€”
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.function
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String function;

    /**
     * Database Column Remarks:
     *   ä»·æ ¼
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.price
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   ä»·æ ¼å�•ä½�
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.price_unit
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String priceUnit;

    /**
     * Database Column Remarks:
     *   é‡‡è´­åœ°ï¼ˆå›½äº§ã€�è¿›å�£ï¼‰
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.local_source
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String localSource;

    /**
     * Database Column Remarks:
     *   ä»ªå™¨çŠ¶æ€�ï¼ˆæ–°è´­å…¥ 0ã€�æ­£å¸¸ 1ã€�ä¸�å�ˆæ ¼ 2ã€�ç»´ä¿® 3ã€�å°�å­˜ 4ã€�æŠ¥åºŸ 5ã€�å€Ÿå‡º 6ã€�è°ƒä¿® 7ï¼‰
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.facility_state
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String facilityState;

    /**
     * Database Column Remarks:
     *   æ˜¯å�¦æ£€æµ‹ 0 ä¸�è®¸æ£€æµ‹ 1 å�¯æ£€æµ‹
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.if_test
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String ifTest;

    /**
     * Database Column Remarks:
     *   è´­ä¹°æ—¥æœŸ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.purchase_date
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private Date purchaseDate;

    /**
     * Database Column Remarks:
     *   æœ‰æ•ˆæ—¥æœŸ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.expiration_date
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private Date expirationDate;

    /**
     * Database Column Remarks:
     *   ä»ªå™¨é™„ä»¶
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.facility_attach
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String facilityAttach;

    /**
     * Database Column Remarks:
     *   ä¿�ç®¡äºº
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.keeper
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String keeper;

    /**
     * Database Column Remarks:
     *   ä¸Šæ¬¡æ£€æµ‹çŠ¶æ€�(å¾…æ£€0åœ¨æ£€1,é€€æ£€3,å®Œæ£€2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.last_test_status
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String lastTestStatus;

    /**
     * Database Column Remarks:
     *   ä¸Šæ¬¡æ£€æµ‹æ—¥æœŸ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.last_test_date
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private Date lastTestDate;

    /**
     * Database Column Remarks:
     *   ä¸Šæ¬¡æ£€æµ‹æ˜¯å�¦å�ˆæ ¼
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.last_test_result
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String lastTestResult;

    /**
     * Database Column Remarks:
     *   æœ€å�Žä¸€æ¬¡å§”æ‰˜å�•id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.last_entrust_id
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String lastEntrustId;

    /**
     * Database Column Remarks:
     *   æœ€å�Žä¸€æ¬¡ä»»åŠ¡id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.last_task_id
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String lastTaskId;

    /**
     * Database Column Remarks:
     *   ä¸Šæ¬¡æŠ¥ä»·
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.last_expect_price
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private BigDecimal lastExpectPrice;

    /**
     * Database Column Remarks:
     *   ä¸Šæ¬¡å®žé™…ä»·
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.last_real_price
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private BigDecimal lastRealPrice;

    /**
     * Database Column Remarks:
     *   å¤‡æ³¨
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.note
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String note;

    /**
     * Database Column Remarks:
     *   æ“�ä½œäºº
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.operater
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private String operater;

    /**
     * Database Column Remarks:
     *   æ›´æ–°æ—¶é—´
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_facility.update_time
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.id
     *
     * @return the value of tb_facility.id
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.id
     *
     * @param id the value for tb_facility.id
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.cid
     *
     * @return the value of tb_facility.cid
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.cid
     *
     * @param cid the value for tb_facility.cid
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.cid
     *
     * @param cid the value for tb_facility.cid
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setCid(Long cid) {
        this.cid = cid.intValue();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.factory_no
     *
     * @return the value of tb_facility.factory_no
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getFactoryNo() {
        return factoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.factory_no
     *
     * @param factoryNo the value for tb_facility.factory_no
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setFactoryNo(String factoryNo) {
        this.factoryNo = factoryNo == null ? null : factoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.facility_name
     *
     * @return the value of tb_facility.facility_name
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getFacilityName() {
        return facilityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.facility_name
     *
     * @param facilityName the value for tb_facility.facility_name
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setFacilityName(String facilityName) {
        this.facilityName = facilityName == null ? null : facilityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.facility_type
     *
     * @return the value of tb_facility.facility_type
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getFacilityType() {
        return facilityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.facility_type
     *
     * @param facilityType the value for tb_facility.facility_type
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setFacilityType(String facilityType) {
        this.facilityType = facilityType == null ? null : facilityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.model
     *
     * @return the value of tb_facility.model
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.model
     *
     * @param model the value for tb_facility.model
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.accuracy
     *
     * @return the value of tb_facility.accuracy
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getAccuracy() {
        return accuracy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.accuracy
     *
     * @param accuracy the value for tb_facility.accuracy
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setAccuracy(String accuracy) {
        this.accuracy = accuracy == null ? null : accuracy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.test_range
     *
     * @return the value of tb_facility.test_range
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getTestRange() {
        return testRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.test_range
     *
     * @param testRange the value for tb_facility.test_range
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setTestRange(String testRange) {
    	if(testRange == null || testRange.trim().isEmpty()) {
    		this.testRange = null;
    	} else {
    		this.testRange = testRange;
    	}
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.belong_organ
     *
     * @return the value of tb_facility.belong_organ
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getBelongOrgan() {
        return belongOrgan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.belong_organ
     *
     * @param belongOrgan the value for tb_facility.belong_organ
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setBelongOrgan(String belongOrgan) {
        this.belongOrgan = belongOrgan == null ? null : belongOrgan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.manage_no
     *
     * @return the value of tb_facility.manage_no
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getManageNo() {
        return manageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.manage_no
     *
     * @param manageNo the value for tb_facility.manage_no
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setManageNo(String manageNo) {
        this.manageNo = manageNo == null ? null : manageNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.manufacturer
     *
     * @return the value of tb_facility.manufacturer
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.manufacturer
     *
     * @param manufacturer the value for tb_facility.manufacturer
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.use_place
     *
     * @return the value of tb_facility.use_place
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getUsePlace() {
        return usePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.use_place
     *
     * @param usePlace the value for tb_facility.use_place
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setUsePlace(String usePlace) {
        this.usePlace = usePlace == null ? null : usePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.function
     *
     * @return the value of tb_facility.function
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getFunction() {
        return function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.function
     *
     * @param function the value for tb_facility.function
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setFunction(String function) {
        this.function = function == null ? null : function.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.price
     *
     * @return the value of tb_facility.price
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.price
     *
     * @param price the value for tb_facility.price
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.price_unit
     *
     * @return the value of tb_facility.price_unit
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getPriceUnit() {
        return priceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.price_unit
     *
     * @param priceUnit the value for tb_facility.price_unit
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setPriceUnit(String priceUnit) {
        this.priceUnit = priceUnit == null ? null : priceUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.local_source
     *
     * @return the value of tb_facility.local_source
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getLocalSource() {
        return localSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.local_source
     *
     * @param localSource the value for tb_facility.local_source
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setLocalSource(String localSource) {
        this.localSource = localSource == null ? null : localSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.facility_state
     *
     * @return the value of tb_facility.facility_state
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getFacilityState() {
        return facilityState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.facility_state
     *
     * @param facilityState the value for tb_facility.facility_state
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setFacilityState(String facilityState) {
        this.facilityState = facilityState == null ? null : facilityState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.if_test
     *
     * @return the value of tb_facility.if_test
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getIfTest() {
        return ifTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.if_test
     *
     * @param ifTest the value for tb_facility.if_test
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setIfTest(String ifTest) {
        this.ifTest = ifTest == null ? null : ifTest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.purchase_date
     *
     * @return the value of tb_facility.purchase_date
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public Date getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.purchase_date
     *
     * @param purchaseDate the value for tb_facility.purchase_date
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.expiration_date
     *
     * @return the value of tb_facility.expiration_date
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.expiration_date
     *
     * @param expirationDate the value for tb_facility.expiration_date
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.facility_attach
     *
     * @return the value of tb_facility.facility_attach
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getFacilityAttach() {
        return facilityAttach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.facility_attach
     *
     * @param facilityAttach the value for tb_facility.facility_attach
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setFacilityAttach(String facilityAttach) {
        this.facilityAttach = facilityAttach == null ? null : facilityAttach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.keeper
     *
     * @return the value of tb_facility.keeper
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getKeeper() {
        return keeper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.keeper
     *
     * @param keeper the value for tb_facility.keeper
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setKeeper(String keeper) {
        this.keeper = keeper == null ? null : keeper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.last_test_status
     *
     * @return the value of tb_facility.last_test_status
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getLastTestStatus() {
        return lastTestStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.last_test_status
     *
     * @param lastTestStatus the value for tb_facility.last_test_status
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setLastTestStatus(String lastTestStatus) {
        this.lastTestStatus = lastTestStatus == null ? null : lastTestStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.last_test_date
     *
     * @return the value of tb_facility.last_test_date
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public Date getLastTestDate() {
        return lastTestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.last_test_date
     *
     * @param lastTestDate the value for tb_facility.last_test_date
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setLastTestDate(Date lastTestDate) {
        this.lastTestDate = lastTestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.last_test_result
     *
     * @return the value of tb_facility.last_test_result
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getLastTestResult() {
        return lastTestResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.last_test_result
     *
     * @param lastTestResult the value for tb_facility.last_test_result
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setLastTestResult(String lastTestResult) {
        this.lastTestResult = lastTestResult == null ? null : lastTestResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.last_entrust_id
     *
     * @return the value of tb_facility.last_entrust_id
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getLastEntrustId() {
        return lastEntrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.last_entrust_id
     *
     * @param lastEntrustId the value for tb_facility.last_entrust_id
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setLastEntrustId(String lastEntrustId) {
        this.lastEntrustId = lastEntrustId == null ? null : lastEntrustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.last_task_id
     *
     * @return the value of tb_facility.last_task_id
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getLastTaskId() {
        return lastTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.last_task_id
     *
     * @param lastTaskId the value for tb_facility.last_task_id
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setLastTaskId(String lastTaskId) {
        this.lastTaskId = lastTaskId == null ? null : lastTaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.last_expect_price
     *
     * @return the value of tb_facility.last_expect_price
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public BigDecimal getLastExpectPrice() {
        return lastExpectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.last_expect_price
     *
     * @param lastExpectPrice the value for tb_facility.last_expect_price
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setLastExpectPrice(BigDecimal lastExpectPrice) {
        this.lastExpectPrice = lastExpectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.last_real_price
     *
     * @return the value of tb_facility.last_real_price
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public BigDecimal getLastRealPrice() {
        return lastRealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.last_real_price
     *
     * @param lastRealPrice the value for tb_facility.last_real_price
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setLastRealPrice(BigDecimal lastRealPrice) {
        this.lastRealPrice = lastRealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.note
     *
     * @return the value of tb_facility.note
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.note
     *
     * @param note the value for tb_facility.note
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.operater
     *
     * @return the value of tb_facility.operater
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public String getOperater() {
        return operater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.operater
     *
     * @param operater the value for tb_facility.operater
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setOperater(String operater) {
        this.operater = operater == null ? null : operater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_facility.update_time
     *
     * @return the value of tb_facility.update_time
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_facility.update_time
     *
     * @param updateTime the value for tb_facility.update_time
     *
     * @mbg.generated Thu Feb 22 19:44:41 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    String cidInit;
    String cidNameInit;
    String facilityTypeInit;
    String facilityNameInit;
    String modelInit;
    String accuracyInit;
    String testRangeInit;
    String facilityStateInit;
    String facilityStateNameInit;
    String ifTestInit;
    String ifTestNameInit;
    private String companyName;

	public String getCidInit() {
		return cidInit;
	}

	public void setCidInit(String cidInit) {
		this.cidInit = cidInit;
	}

	public String getCidNameInit() {
		return cidNameInit;
	}

	public void setCidNameInit(String cidNameInit) {
		this.cidNameInit = cidNameInit;
	}

	public String getFacilityTypeInit() {
		return facilityTypeInit;
	}

	public void setFacilityTypeInit(String facilityTypeInit) {
		this.facilityTypeInit = facilityTypeInit;
	}

	public String getFacilityNameInit() {
		return facilityNameInit;
	}

	public void setFacilityNameInit(String facilityNameInit) {
		this.facilityNameInit = facilityNameInit;
	}

	public String getModelInit() {
		return modelInit;
	}

	public void setModelInit(String modelInit) {
		this.modelInit = modelInit;
	}

	public String getAccuracyInit() {
		return accuracyInit;
	}

	public void setAccuracyInit(String accuracyInit) {
		this.accuracyInit = accuracyInit;
	}

	public String getTestRangeInit() {
		return testRangeInit;
	}

	public void setTestRangeInit(String testRangeInit) {
		this.testRangeInit = testRangeInit;
	}

	public String getFacilityStateInit() {
		return facilityStateInit;
	}

	public void setFacilityStateInit(String facilityStateInit) {
		this.facilityStateInit = facilityStateInit;
	}

	public String getFacilityStateNameInit() {
		return facilityStateNameInit;
	}

	public void setFacilityStateNameInit(String facilityStateNameInit) {
		this.facilityStateNameInit = facilityStateNameInit;
	}

	public String getIfTestInit() {
		return ifTestInit;
	}

	public void setIfTestInit(String ifTestInit) {
		this.ifTestInit = ifTestInit;
	}

	public String getIfTestNameInit() {
		return ifTestNameInit;
	}

	public void setIfTestNameInit(String ifTestNameInit) {
		this.ifTestNameInit = ifTestNameInit;
	}
	String baseUri;
	String pageNum;
	String pageSize;
	String orderByColumn;
	String orderByType;

	public String getBaseUri() {
		return baseUri;
	}

	public void setBaseUri(String baseUri) {
		this.baseUri = baseUri;
	}

	public String getPageNum() {
		return pageNum;
	}

	public void setPageNum(String pageNum) {
		this.pageNum = pageNum;
	}

	public String getPageSize() {
		return pageSize;
	}

	public void setPageSize(String pageSize) {
		this.pageSize = pageSize;
	}

	public String getOrderByColumn() {
		return orderByColumn;
	}

	public void setOrderByColumn(String orderByColumn) {
		this.orderByColumn = orderByColumn;
	}

	public String getOrderByType() {
		return orderByType;
	}

	public void setOrderByType(String orderByType) {
		this.orderByType = orderByType;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
}