package com.webside.business.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   å¼ºæ£€å§”æ‰˜å�•
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_enforce_entrust
 *
 * @mbg.generated do_not_delete_during_merge Sun Feb 25 15:41:32 CST 2018
 */
public class EnforceEntrustEntity {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.id
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private String id;

    /**
     * Database Column Remarks:
     *   å§”æ‰˜å�•å��ç§°
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.name
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private String name;

    /**
     * Database Column Remarks:
     *   ä»»åŠ¡id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.task_id
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private String taskId;

    /**
     * Database Column Remarks:
     *   ä¼�ä¸šid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.cid
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private Integer cid;

    /**
     * Database Column Remarks:
     *   æ£€æµ‹æœºæž„id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.organ_id
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private Integer organId;

    /**
     * Database Column Remarks:
     *   è�”ç³»äºº
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.contacter
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private String contacter;

    /**
     * Database Column Remarks:
     *   è�”ç³»ç”µè¯�
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.contact_phone
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private String contactPhone;

    /**
     * Database Column Remarks:
     *   è�”ç³»åœ°å�€
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.contact_address
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private String contactAddress;

    /**
     * Database Column Remarks:
     *   é‚®æ”¿ç¼–ç �
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.postcode
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private String postcode;

    /**
     * Database Column Remarks:
     *   å¡«æŠ¥æ—¥æœŸ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.import_date
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private Date importDate;

    /**
     * Database Column Remarks:
     *   ç”³è¯·äºº
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.proposer
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private String proposer;

    /**
     * Database Column Remarks:
     *   å§”æ‰˜æ—¥æœŸ(ç”³)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.propose_date
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private Date proposeDate;

    /**
     * Database Column Remarks:
     *   é¢†å�–äºº
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.receiver
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private String receiver;

    /**
     * Database Column Remarks:
     *   é¢†å�–æ—¥æœŸï¼ˆé¢†ï¼‰
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.receive_date
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private Date receiveDate;

    /**
     * Database Column Remarks:
     *   é™„ä»¶
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.attachment
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private String attachment;

    /**
     * Database Column Remarks:
     *   æ˜¯å�¦å®Œæ£€ 1 å®Œæˆ� 0 æœªå®Œæˆ�
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.if_over
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private String ifOver;

    /**
     * Database Column Remarks:
     *   æ˜¯å�¦å¼ºæ£€å§”æ‰˜å�• 1 æ˜¯ 0 å�¦
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.if_enforce
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private String ifEnforce;

    /**
     * Database Column Remarks:
     *   æ›´æ–°æ—¶é—´
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enforce_entrust.update_time
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.id
     *
     * @return the value of tb_enforce_entrust.id
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.id
     *
     * @param id the value for tb_enforce_entrust.id
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.name
     *
     * @return the value of tb_enforce_entrust.name
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.name
     *
     * @param name the value for tb_enforce_entrust.name
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.task_id
     *
     * @return the value of tb_enforce_entrust.task_id
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.task_id
     *
     * @param taskId the value for tb_enforce_entrust.task_id
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.cid
     *
     * @return the value of tb_enforce_entrust.cid
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.cid
     *
     * @param cid the value for tb_enforce_entrust.cid
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.organ_id
     *
     * @return the value of tb_enforce_entrust.organ_id
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public Integer getOrganId() {
        return organId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.organ_id
     *
     * @param organId the value for tb_enforce_entrust.organ_id
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setOrganId(Integer organId) {
        this.organId = organId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.contacter
     *
     * @return the value of tb_enforce_entrust.contacter
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public String getContacter() {
        return contacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.contacter
     *
     * @param contacter the value for tb_enforce_entrust.contacter
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setContacter(String contacter) {
        this.contacter = contacter == null ? null : contacter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.contact_phone
     *
     * @return the value of tb_enforce_entrust.contact_phone
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.contact_phone
     *
     * @param contactPhone the value for tb_enforce_entrust.contact_phone
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.contact_address
     *
     * @return the value of tb_enforce_entrust.contact_address
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.contact_address
     *
     * @param contactAddress the value for tb_enforce_entrust.contact_address
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress == null ? null : contactAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.postcode
     *
     * @return the value of tb_enforce_entrust.postcode
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.postcode
     *
     * @param postcode the value for tb_enforce_entrust.postcode
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.import_date
     *
     * @return the value of tb_enforce_entrust.import_date
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public Date getImportDate() {
        return importDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.import_date
     *
     * @param importDate the value for tb_enforce_entrust.import_date
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setImportDate(Date importDate) {
        this.importDate = importDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.proposer
     *
     * @return the value of tb_enforce_entrust.proposer
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public String getProposer() {
        return proposer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.proposer
     *
     * @param proposer the value for tb_enforce_entrust.proposer
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setProposer(String proposer) {
        this.proposer = proposer == null ? null : proposer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.propose_date
     *
     * @return the value of tb_enforce_entrust.propose_date
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public Date getProposeDate() {
        return proposeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.propose_date
     *
     * @param proposeDate the value for tb_enforce_entrust.propose_date
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setProposeDate(Date proposeDate) {
        this.proposeDate = proposeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.receiver
     *
     * @return the value of tb_enforce_entrust.receiver
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.receiver
     *
     * @param receiver the value for tb_enforce_entrust.receiver
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.receive_date
     *
     * @return the value of tb_enforce_entrust.receive_date
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public Date getReceiveDate() {
        return receiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.receive_date
     *
     * @param receiveDate the value for tb_enforce_entrust.receive_date
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setReceiveDate(Date receiveDate) {
        this.receiveDate = receiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.attachment
     *
     * @return the value of tb_enforce_entrust.attachment
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.attachment
     *
     * @param attachment the value for tb_enforce_entrust.attachment
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.if_over
     *
     * @return the value of tb_enforce_entrust.if_over
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public String getIfOver() {
        return ifOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.if_over
     *
     * @param ifOver the value for tb_enforce_entrust.if_over
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setIfOver(String ifOver) {
        this.ifOver = ifOver == null ? null : ifOver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.if_enforce
     *
     * @return the value of tb_enforce_entrust.if_enforce
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public String getIfEnforce() {
        return ifEnforce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.if_enforce
     *
     * @param ifEnforce the value for tb_enforce_entrust.if_enforce
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setIfEnforce(String ifEnforce) {
        this.ifEnforce = ifEnforce == null ? null : ifEnforce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enforce_entrust.update_time
     *
     * @return the value of tb_enforce_entrust.update_time
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enforce_entrust.update_time
     *
     * @param updateTime the value for tb_enforce_entrust.update_time
     *
     * @mbg.generated Sun Feb 25 15:41:32 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}